apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: baalvion-singularity-mesh
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: zurich-ch-01
        url: https://api.ch.baalvion.gov
        region: europe
      - cluster: singapore-sg-01
        url: https://api.sg.baalvion.gov
        region: apac
      - cluster: ashburn-us-01
        url: https://api.us.baalvion.gov
        region: americas
  template:
    metadata:
      name: '{{cluster}}-core-grid'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/baalvion/infrastructure.git'
        targetRevision: HEAD
        path: kubernetes/manifests/singularity
        helm:
          parameters:
          - name: "global.region"
            value: "{{region}}"
          - name: "global.clusterId"
            value: "{{cluster}}"
          - name: "global.integrityLevel"
            value: "SUPREME"
      destination:
        server: '{{url}}'
        namespace: singularity-core
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
