'use strict';
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('commerce_products', {
        id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
        storeId: { type: DataTypes.UUID, allowNull: false, references: { model: { tableName: 'commerce_stores', schema: 'commerce' }, key: 'id' }, onDelete: 'CASCADE' },
        categoryId: { type: DataTypes.UUID, allowNull: true, references: { model: { tableName: 'commerce_categories', schema: 'commerce' }, key: 'id' }, onDelete: 'SET NULL' },
        createdBy: { type: DataTypes.BIGINT, allowNull: false },
        lastEditedBy: { type: DataTypes.BIGINT, allowNull: true },
        name: { type: DataTypes.STRING(500), allowNull: false },
        slug: { type: DataTypes.STRING(500), allowNull: false },
        shortDescription: { type: DataTypes.TEXT, allowNull: true },
        description: { type: DataTypes.TEXT, allowNull: true },
        productType: { type: DataTypes.ENUM('simple', 'variable', 'grouped', 'bundle', 'digital'), defaultValue: 'simple' },
        status: { type: DataTypes.ENUM('draft', 'pending_review', 'approved', 'published', 'archived'), defaultValue: 'draft' },
        visibility: { type: DataTypes.ENUM('public', 'private', 'password'), defaultValue: 'public' },
        sku: { type: DataTypes.STRING(200), allowNull: true },
        barcode: { type: DataTypes.STRING(100), allowNull: true },
        weight: { type: DataTypes.DECIMAL(10, 3), allowNull: true },
        weightUnit: { type: DataTypes.STRING(10), defaultValue: 'kg' },
        dimensions: { type: DataTypes.JSONB, allowNull: true },
        materials: { type: DataTypes.ARRAY(DataTypes.TEXT), defaultValue: [] },
        specifications: { type: DataTypes.JSONB, defaultValue: {} },
        seoMetadata: { type: DataTypes.JSONB, defaultValue: {} },
        tags: { type: DataTypes.ARRAY(DataTypes.TEXT), defaultValue: [] },
        customFields: { type: DataTypes.JSONB, defaultValue: {} },
        isFeatured: { type: DataTypes.BOOLEAN, defaultValue: false },
        isDigital: { type: DataTypes.BOOLEAN, defaultValue: false },
        requiresShipping: { type: DataTypes.BOOLEAN, defaultValue: true },
        // First-class inventory (promoted from custom_fields.stock). Order-time decrement is owned
        // by order-service; this is the catalog-side source of truth + storefront availability.
        stockQuantity: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
        trackInventory: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
        allowBackorder: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
        downloadLimit: { type: DataTypes.INTEGER, allowNull: true },
        downloadExpiry: { type: DataTypes.INTEGER, allowNull: true },
        relatedProductIds: { type: DataTypes.ARRAY(DataTypes.UUID), defaultValue: [] },
        upsellProductIds: { type: DataTypes.ARRAY(DataTypes.UUID), defaultValue: [] },
        crossSellProductIds: { type: DataTypes.ARRAY(DataTypes.UUID), defaultValue: [] },
        viewCount: { type: DataTypes.BIGINT, defaultValue: 0 },
        revisionCount: { type: DataTypes.INTEGER, defaultValue: 0 },
        publishedAt: { type: DataTypes.DATE, allowNull: true },
    }, {
        schema: 'commerce', tableName: 'commerce_products', underscored: true, timestamps: true,
        indexes: [
            { unique: true, fields: ['store_id', 'slug'] },
            { fields: ['store_id'] }, { fields: ['category_id'] },
            { fields: ['status'] }, { fields: ['product_type'] },
            { fields: ['is_featured'] }, { fields: ['published_at'] },
        ],
    });
};
