apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc.name" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels: {{- include "svc.selector" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "svc.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
    spec:
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: {{ include "svc.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toJson . }}
          {{- end }}
          ports:
            - { name: http, containerPort: {{ .Values.containerPort }} }
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- range .Values.secretRefs }}
            - name: {{ .name }}
              valueFrom: { secretKeyRef: { name: {{ .secret.name }}, key: {{ .secret.key }} } }
            {{- end }}
          readinessProbe:
            httpGet: { path: {{ .Values.probes.readinessPath }}, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: {{ .Values.probes.livenessPath }}, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
