module.exports = function (sequelize, DataTypes) {
    return sequelize.define('influencer_profiles', {
        id: { type: DataTypes.BIGINT, autoIncrement: true, primaryKey: true },
        user_id: { type: DataTypes.BIGINT, allowNull: false },
        org_id: { type: DataTypes.UUID, allowNull: false },
        display_name: { type: DataTypes.STRING(255), allowNull: false },
        bio: { type: DataTypes.TEXT, allowNull: true },
        avatar_url: { type: DataTypes.TEXT, allowNull: true },
        niche: { type: DataTypes.JSONB, defaultValue: [] },
        platforms: { type: DataTypes.JSONB, defaultValue: [] },
        follower_count_instagram: { type: DataTypes.INTEGER, defaultValue: 0 },
        follower_count_youtube: { type: DataTypes.INTEGER, defaultValue: 0 },
        follower_count_twitter: { type: DataTypes.INTEGER, defaultValue: 0 },
        follower_count_tiktok: { type: DataTypes.INTEGER, defaultValue: 0 },
        engagement_rate: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },
        avg_views_per_post: { type: DataTypes.INTEGER, defaultValue: 0 },
        rate_per_post: { type: DataTypes.BIGINT, allowNull: true },
        rate_per_story: { type: DataTypes.BIGINT, allowNull: true },
        rate_per_video: { type: DataTypes.BIGINT, allowNull: true },
        currency: { type: DataTypes.STRING(10), defaultValue: 'INR' },
        location: { type: DataTypes.STRING(255), allowNull: true },
        languages: { type: DataTypes.JSONB, defaultValue: [] },
        verified: { type: DataTypes.BOOLEAN, defaultValue: false },
        status: { type: DataTypes.STRING(32), defaultValue: 'active' },
        total_earned: { type: DataTypes.BIGINT, defaultValue: 0 },
        campaigns_completed: { type: DataTypes.INTEGER, defaultValue: 0 },
    }, {
        tableName: 'influencer_profiles',
        schema: 'brand',
        timestamps: true,
        underscored: true,
        indexes: [
            { fields: ['user_id'] },
            { fields: ['org_id'] },
            { fields: ['status'] },
            { fields: ['verified'] },
            { fields: ['location'] },
        ],
    });
};
