// ============================================================================
// Baalvion local stack — PM2 process definitions
// ----------------------------------------------------------------------------
// Source of truth for the FULL local fleet (43 processes), regenerated from the
// live running fleet (`~/.pm2/dump.pm2`) on 2026-06-13 so it matches reality.
//
//   pm2 start ecosystem.config.js          # cold-start everything
//   pm2 start ecosystem.config.js --only X # start one app
//   pm2 save                               # persist to dump (what `pm2 resurrect` restores on reboot)
//
// IMPORTANT NOTES
//  * Datastores run in DOCKER, not here: postgres (:5432), redis (:6379), the
//    financial postgres/redis (:5433/:6380), pgadmin. Start them first via the
//    compose files and wait for (healthy).
//  * Docker-OWNED services are intentionally ABSENT here (single owner = Docker):
//    cms-service (:3011), law-service, payment-service, rbac-service. Do NOT add
//    them — a PM2 copy races Docker for the port and crash-loops.
//  * Frontends vary by mode: those running `start` (Next) or `preview` (Vite)
//    serve a PRODUCTION build — run `pnpm build` first (valid .next/ or dist/) or
//    they crash-loop. Those running `dev` compile on the fly (no prebuild needed).
//  * STARTUP STORM WARNING: `pm2 start ecosystem.config.js` launches every app at
//    once. The DB-backed services will hammer Postgres simultaneously and can
//    crash-loop on "the database system is starting up". If that happens, bring
//    them back one at a time (`pm2 restart <name>` sequentially), not all at once.
// ============================================================================

module.exports = {
  apps: [
    // ── Backend services ────────────────────────────────────────────────
    {
      name: "about-service",
      cwd: "./Backend/services/ecosystem/about-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "admin-service",
      cwd: "./Backend/services/platform/admin-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "auth-gateway",
      cwd: "./Backend/services/identity/auth-gateway",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "auth-service",
      cwd: "./Backend/services/identity/auth-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "brand-connector-service",
      cwd: "./Backend/services/ecosystem/brand-connector-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "commerce-service",
      cwd: "./Backend/services/commerce/commerce-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // No own node_modules — borrows ir-service via NODE_PATH. Schema `crm`, brand-scoped (amarise-luxe).
    {
      name: "crm-service",
      cwd: "./Backend/services/ecosystem/crm-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "development", PORT: "3063", NODE_PATH: require('path').join(__dirname, 'Backend/services/ecosystem/ir-service/node_modules') },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "ctm-service",
      cwd: "./Backend/services/ecosystem/ctm-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "dashboard-service",
      cwd: "./Backend/services/platform/dashboard-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "fulfillment-service",
      cwd: "./Backend/services/commerce/fulfillment-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "development", PORT: "3016" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "imperialpedia-service",
      cwd: "./Backend/services/knowledge/imperialpedia-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "insiders-service",
      cwd: "./Backend/services/ecosystem/insiders-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "inventory-service",
      cwd: "./Backend/services/commerce/inventory-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "ir-service",
      cwd: "./Backend/services/ecosystem/ir-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "jobs-service",
      cwd: "./Backend/services/ecosystem/jobs-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "market-service",
      cwd: "./Backend/services/commerce/market-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // No own node_modules — borrows ir-service via NODE_PATH (same precedent as crm-service).
    {
      name: "marketplace-service",
      cwd: "./Backend/services/marketplace/marketplace-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "production", NODE_PATH: require('path').join(__dirname, 'Backend/services/ecosystem/ir-service/node_modules') },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "mining-service",
      cwd: "./Backend/services/ecosystem/mining-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "notification-service",
      cwd: "./Backend/services/infrastructure/notification-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "oauth-service",
      cwd: "./Backend/services/identity/oauth-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // order-service REMOVED (finance consolidation) — the Node order-service was deleted;
    // order lifecycle is owned by trade/order-execution-service. Do not re-add from a PM2 dump.
    {
      name: "proxy-service",
      cwd: "./Backend/services/infrastructure/proxy-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "real-estate-service",
      cwd: "./Backend/services/ecosystem/real-estate-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // Borrows pg/ioredis/jsonwebtoken from session-service via NODE_PATH (no own node_modules).
    {
      name: "realtime-service",
      cwd: "./Backend/services/platform/realtime-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development", NODE_PATH: require('path').join(__dirname, 'Backend/services/identity/session-service/node_modules') },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "session-service",
      cwd: "./Backend/services/identity/session-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "trade-service",
      cwd: "./Backend/services/commerce/trade-service",
      script: "./index.js",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "600M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },

    // ── Frontends ───────────────────────────────────────────────────────
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "about-web",
      cwd: "./Frontend/about-baalvion-main",
      script: "./node_modules/next/dist/bin/next",
      args: "start -p 3020",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "production", PORT: "3020" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "admin-platform",
      cwd: "./Frontend/admin-platform",
      script: "./node_modules/next/dist/bin/next",
      args: "start --port 3030",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "production" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "amarise-web",
      cwd: "./Frontend/AmariseMaisonAvenue-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3033",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "baalvion-com-web",
      cwd: "./Frontend/baalvion-com-main",
      script: "./node_modules/next/dist/bin/next",
      // Serves on :3043 (moved off :3040, which is the realtime-service contract port —
      // gateway dynamic.yml, root docker-compose, openapi all map realtime to :3040).
      args: "start -p 3043",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "production", PORT: "3043" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "brand-web",
      cwd: "./Frontend/brand-connector-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3035",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "ctm-web",
      cwd: "./Frontend/controlthemarket-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3034",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "dashboard-web",
      cwd: "./Frontend/company-unified-Dashboard-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3024",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "elite-circle-web",
      cwd: "./Frontend/baalvion-elite-circle-main",
      script: "./node_modules/vite/bin/vite.js",
      args: "preview --port 8081 --host",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "800M",
      env: { NODE_ENV: "production" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "founders-web",
      cwd: "./Frontend/For Invstors and Founders",
      script: "./node_modules/vite/bin/vite.js",
      args: "preview --port 8082 --host",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "gti-web",
      cwd: "./Frontend/Global-Trade-Infrastructure-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 9003",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "imperialpedia-web",
      cwd: "./Frontend/Imperialpedia-main",
      script: "./node_modules/next/dist/bin/next",
      args: "start -p 3029",
      interpreter: "node",
      watch: false,
      autorestart: true,
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "insiders-seo-web",
      cwd: "./Frontend/insiders-seo",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3060",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "ir-web",
      cwd: "./Frontend/IR-Baalvion-main",
      script: "./node_modules/next/dist/bin/next",
      args: "start -p 3027",
      interpreter: "node",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "production", PORT: "3027" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "jobs-web",
      cwd: "./Frontend/Baalvion-Jobs-Portal-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3037",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "law-web",
      cwd: "./Frontend/Law-Elite-Network-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 9002",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "1500M",
      env: { NODE_ENV: "development" },
      log_date_format: 'HH:mm:ss',
    },
    {
      name: "mining-web",
      cwd: "./Frontend/Mining.Baalvion-main",
      script: "./node_modules/next/dist/bin/next",
      args: "dev -p 3028",
      interpreter: "node",
      watch: false,
      autorestart: true,
      log_date_format: 'HH:mm:ss',
    },
    // Production build — run `pnpm build` (valid .next/dist) BEFORE start, or it crash-loops.
    {
      name: "proxy-web",
      cwd: "./Frontend/Proxy-BaalvionStack",
      script: "./node_modules/vite/bin/vite.js",
      args: "preview --port 8080 --host",
      interpreter: "node",
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: 'HH:mm:ss',
    },
  ],
};
