'use strict';
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('properties', {
        id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
        org_id: { type: DataTypes.UUID, allowNull: true },
        agent_id: { type: DataTypes.INTEGER, allowNull: true, references: { model: { tableName: 'agents', schema: 'real_estate' }, key: 'id' } },
        title: { type: DataTypes.STRING(500), allowNull: false },
        description: { type: DataTypes.TEXT, allowNull: true },
        property_type: { type: DataTypes.ENUM('apartment', 'villa', 'house', 'commercial', 'plot', 'office'), defaultValue: 'apartment' },
        listing_type: { type: DataTypes.ENUM('sale', 'rent', 'lease'), defaultValue: 'sale' },
        price: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
        currency: { type: DataTypes.STRING(10), defaultValue: 'USD' },
        bedrooms: { type: DataTypes.INTEGER, defaultValue: 0 },
        bathrooms: { type: DataTypes.INTEGER, defaultValue: 0 },
        area_sqft: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
        area_sqm: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
        floor_number: { type: DataTypes.INTEGER, allowNull: true },
        total_floors: { type: DataTypes.INTEGER, allowNull: true },
        year_built: { type: DataTypes.INTEGER, allowNull: true },
        country: { type: DataTypes.STRING(100), allowNull: true },
        city: { type: DataTypes.STRING(100), allowNull: true },
        area: { type: DataTypes.STRING(200), allowNull: true },
        address: { type: DataTypes.TEXT, allowNull: true },
        latitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
        longitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
        amenities: { type: DataTypes.JSONB, defaultValue: [] },
        features: { type: DataTypes.JSONB, defaultValue: {} },
        status: { type: DataTypes.ENUM('draft', 'active', 'under_offer', 'sold', 'rented', 'archived'), defaultValue: 'draft' },
        is_featured: { type: DataTypes.BOOLEAN, defaultValue: false },
        views_count: { type: DataTypes.INTEGER, defaultValue: 0 },
        inquiry_count: { type: DataTypes.INTEGER, defaultValue: 0 },
    }, {
        tableName: 'properties',
        schema: 'real_estate',
        timestamps: true,
        underscored: true,
        indexes: [
            { fields: ['org_id'] },
            { fields: ['agent_id'] },
            { fields: ['status'] },
            { fields: ['property_type'] },
            { fields: ['listing_type'] },
            { fields: ['city'] },
            { fields: ['country'] },
            { fields: ['price'] },
            { fields: ['is_featured'] },
        ],
    });
};
