'use strict';
/**
 * Real, verified per-brand tokens — sourced from Frontend/auth-baalvion/src/lib/themes.ts
 * (the same registry that themes the shared login page) plus each site's own globals.css
 * where auth-baalvion doesn't cover it yet (proxy/baalvionstack, marketunderworld, law-service's
 * own navy branding). This is the single source of truth for email branding — do not invent
 * new colors here; port them from the live site's real tokens.
 *
 * folder: matches the existing Email Templates/<folder> directory naming.
 * headerBg: the dark chrome band behind the logo + the highlight box background. Dark-mode
 * brands use their own real --bg; light-mode brands get a bespoke deep tint of their accent
 * so the "premium dark band" moment still carries brand identity instead of being generic black.
 * fontDisplay/fontBody: email-safe fallback stacks approximating the brand's real web font
 * (Fraunces/Cormorant/Space Grotesk/Plex Mono don't render in Gmail/Outlook without @font-face,
 * which most clients strip anyway) — pick the closest system serif/sans/mono.
 */

const SANS = `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif`;
const SERIF_WARM = `Georgia, 'Times New Roman', serif`;
const SERIF_LUXE = `Garamond, Baskerville, 'Times New Roman', serif`;
const MONO = `'SF Mono', 'Courier New', monospace`;

const BRANDS = {
  baalvion: {
    folder: 'baalvion',
    brandName: 'Baalvion',
    tagline: 'Global infrastructure intelligence',
    domain: 'https://baalvion.com',
    mode: 'dark',
    accent: '#ff9900',
    accentSoft: '#fff3e0',
    headerBg: '#06080b',
    fontDisplay: SERIF_WARM,
    fontBody: SANS,
    logoMark: `<rect x="1" y="1" width="6" height="6" rx="0.5" fill="white"/><rect x="8" y="1" width="6" height="6" rx="0.5" fill="white" opacity="0.6"/><rect x="1" y="8" width="6" height="6" rx="0.5" fill="white" opacity="0.6"/><rect x="8" y="8" width="6" height="6" rx="0.5" fill="white" opacity="0.3"/>`,
  },
  about: {
    folder: 'about',
    brandName: 'Baalvion',
    tagline: 'Stories, press & guidance',
    domain: 'https://about.baalvion.com',
    mode: 'light',
    accent: '#ff9900',
    accentSoft: '#fff3e0',
    headerBg: '#15171c',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<rect x="1" y="1" width="6" height="6" rx="0.5" fill="white"/><rect x="8" y="1" width="6" height="6" rx="0.5" fill="white" opacity="0.6"/><rect x="1" y="8" width="6" height="6" rx="0.5" fill="white" opacity="0.6"/><rect x="8" y="8" width="6" height="6" rx="0.5" fill="white" opacity="0.3"/>`,
  },
  admin: {
    folder: 'admin',
    brandName: 'Baalvion Admin',
    tagline: 'Platform administration',
    domain: 'https://admin.baalvion.com',
    mode: 'light',
    accent: '#3b82f6',
    accentSoft: '#eaf1ff',
    headerBg: '#0f172a',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<rect x="1" y="1" width="12" height="3" rx="1" fill="white" opacity="0.9"/><rect x="1" y="6" width="8" height="3" rx="1" fill="white" opacity="0.6"/><rect x="1" y="11" width="10" height="3" rx="1" fill="white" opacity="0.4"/>`,
  },
  gti: {
    folder: 'trade',
    brandName: 'Baalvion Trade',
    tagline: 'Global trade infrastructure',
    domain: 'https://trade.baalvion.com',
    mode: 'dark',
    accent: '#5b9efd',
    accentSoft: '#e8f1ff',
    headerBg: '#020617',
    fontDisplay: SANS,
    fontBody: SANS,
    fontMono: MONO,
    logoMark: `<path d="M1 12L5 4L9 9L13 1" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none" opacity="0.9"/>`,
  },
  ir: {
    folder: 'ir',
    brandName: 'Baalvion IR',
    tagline: 'Investor relations',
    domain: 'https://ir.baalvion.com',
    mode: 'dark',
    accent: '#f97316',
    accentSoft: '#fff1e6',
    headerBg: '#050607',
    fontDisplay: SERIF_WARM,
    fontBody: SANS,
    logoMark: `<circle cx="7" cy="8" r="6" stroke="white" stroke-width="1.4" fill="none" opacity="0.85"/><path d="M7 4v4l3 2" stroke="white" stroke-width="1.4" stroke-linecap="round" fill="none" opacity="0.85"/>`,
  },
  mining: {
    folder: 'mining',
    brandName: 'Baalvion Mining',
    tagline: 'Resource infrastructure',
    domain: 'https://mining.baalvion.com',
    mode: 'light',
    accent: '#21cedd',
    accentSoft: '#e3fbfd',
    headerBg: '#0d2b30',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<path d="M2 12L5 5L8 9L11 3L13 12Z" fill="white" opacity="0.85"/>`,
  },
  jobs: {
    folder: 'jobs',
    brandName: 'Baalvion Jobs',
    tagline: 'Careers & talent',
    domain: 'https://jobs.baalvion.com',
    mode: 'light',
    accent: '#3b82f6',
    accentSoft: '#eaf1ff',
    headerBg: '#101826',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<rect x="3" y="5" width="8" height="7" rx="1" stroke="white" stroke-width="1.3" fill="none" opacity="0.9"/><path d="M5.5 5V4a1.5 1.5 0 011.5-1.5h0A1.5 1.5 0 018.5 4v1" stroke="white" stroke-width="1.3" fill="none" opacity="0.9"/>`,
  },
  'brand-connector': {
    folder: 'connect',
    brandName: 'Baalvion Connect',
    tagline: 'The brand network',
    domain: 'https://connect.baalvion.com',
    mode: 'light',
    accent: '#9d6bff',
    accentSoft: '#f2ecff',
    headerBg: '#1a1330',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<circle cx="4" cy="4" r="2.4" fill="white" opacity="0.9"/><circle cx="10" cy="4" r="2.4" fill="white" opacity="0.6"/><circle cx="7" cy="11" r="2.4" fill="white" opacity="0.4"/>`,
  },
  dashboard: {
    folder: 'dashboard',
    brandName: 'Baalvion Dashboard',
    tagline: 'Your company workspace',
    domain: 'https://dashboard.baalvion.com',
    mode: 'light',
    accent: '#4a9dcc',
    accentSoft: '#eaf5fb',
    headerBg: '#0f1923',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<rect x="1" y="1" width="6" height="6" rx="1" fill="white" opacity="0.9"/><rect x="8" y="1" width="6" height="6" rx="1" fill="white" opacity="0.5"/><rect x="1" y="8" width="13" height="6" rx="1" fill="white" opacity="0.3"/>`,
  },
  proxy: {
    folder: 'baalvionstack',
    brandName: 'Baalvion NetStack',
    tagline: 'Enterprise proxy & data network',
    domain: 'https://proxy.baalvionstack.com',
    mode: 'dark',
    accent: '#39e5a8',
    accentSoft: '#e3fbf2',
    headerBg: '#0f1419',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<path d="M7 1L13 4V10L7 13L1 10V4Z" stroke="white" stroke-width="1.3" fill="none" opacity="0.9"/><circle cx="7" cy="7" r="1.6" fill="white" opacity="0.9"/>`,
  },
  amarise: {
    folder: 'amarisemaisonavenue',
    brandName: 'Amarisé',
    tagline: 'Maison Avenue',
    domain: 'https://amarisemaisonavenue.com',
    mode: 'light',
    accent: '#1a1a1a',
    accentSoft: '#f5f5f5',
    headerBg: '#000000',
    fontDisplay: SERIF_LUXE,
    fontBody: SANS,
    logoMark: `<text x="7" y="11" font-family="Garamond, serif" font-size="11" fill="white" text-anchor="middle" opacity="0.95">A</text>`,
  },
  ctm: {
    folder: 'controlthemarket',
    brandName: 'Control The Market',
    tagline: 'Markets infrastructure',
    domain: 'https://controlthemarket.com',
    mode: 'light',
    accent: '#5fa8d3',
    accentSoft: '#eaf5fb',
    headerBg: '#0d1b26',
    fontDisplay: SANS,
    fontBody: SANS,
    logoMark: `<path d="M1 12L4 8L7 10L13 2" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" opacity="0.9"/>`,
  },
  imperialpedia: {
    folder: 'imperialpedia',
    brandName: 'Imperialpedia',
    tagline: 'The knowledge base',
    domain: 'https://imperialpedia.com',
    mode: 'light',
    accent: '#1d4fc4',
    accentSoft: '#eaf0fd',
    headerBg: '#0d1633',
    fontDisplay: SERIF_WARM,
    fontBody: SANS,
    logoMark: `<path d="M7 1h6v14H7zM3 1h3v2H3zM12 1h3v2h-3zM3 13h3v2H3zM12 13h3v2h-3z" fill="white" opacity="0.9"/>`,
  },
  law: {
    folder: 'lawelitenetwork',
    brandName: 'Law Elite Network',
    tagline: 'The legal network',
    domain: 'https://lawelitenetwork.com',
    mode: 'light',
    accent: '#2563eb',
    accentSoft: '#eaf1ff',
    // Matches law-service's own real mailer branding (service/mailer.js), not invented here.
    headerBg: '#0B1F3A',
    fontDisplay: SERIF_WARM,
    fontBody: SANS,
    logoMark: `<path d="M7 1L13 4.2V9.4C13 11.8 10.3 13.3 7 13.8C3.7 13.3 1 11.8 1 9.4V4.2Z" stroke="white" stroke-width="1.2" fill="none" opacity="0.9"/>`,
  },
  marketunderworld: {
    folder: 'marketunderworld',
    brandName: 'Market Underworld',
    tagline: 'Decentralized digital marketplace',
    domain: 'https://marketunderworld.com',
    mode: 'dark',
    accent: '#39FF14',
    accentSoft: '#e8ffe0',
    // Matches the site's own real globals.css --brand-base, not invented here.
    headerBg: '#0B0C0F',
    fontDisplay: SANS,
    fontBody: SANS,
    fontMono: MONO,
    logoMark: `<rect x="1" y="6" width="12" height="2.4" fill="white" opacity="0.9"/><rect x="1" y="2" width="8" height="2.4" fill="white" opacity="0.6"/><rect x="1" y="10" width="10" height="2.4" fill="white" opacity="0.45"/>`,
  },
};

module.exports = { BRANDS };
