package com.baalvion.payment.gateway.config;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;
import org.springframework.stereotype.Component;

/**
 * Externalized PSP credentials and endpoints, bound from the {@code app.psp.*} namespace.
 *
 * <p>Mirrors the Node provider secrets (resolved there from the CMS vault via
 * {@code sdk.config}). In this service they bind from environment variables at deploy time
 * — secrets are NEVER hardcoded. Each provider's {@code base-url} defaults to its public
 * API host; {@code mock} flips deterministic create/refund id generation on for non-prod.
 *
 * <p>Example (application.yml):
 * <pre>
 * app:
 *   psp:
 *     razorpay:
 *       key-id: ${RAZORPAY_KEY_ID:}
 *       key-secret: ${RAZORPAY_KEY_SECRET:}
 *       webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}
 *       base-url: ${RAZORPAY_BASE_URL:https://api.razorpay.com}
 *     stripe:
 *       secret-key: ${STRIPE_SECRET_KEY:}
 *       publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
 *       webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
 *       base-url: ${STRIPE_BASE_URL:https://api.stripe.com}
 *     payu:
 *       merchant-key: ${PAYU_MERCHANT_KEY:}
 *       merchant-salt: ${PAYU_MERCHANT_SALT:}
 *       base-url: ${PAYU_BASE_URL:https://secure.payu.in}
 * </pre>
 */
@Component
@ConfigurationProperties(prefix = "app.psp")
@Data
public class PspProperties {

  /** When true, providers generate deterministic mock order/refund ids (no live merchant call). */
  private boolean mock = false;

  @NestedConfigurationProperty
  private Razorpay razorpay = new Razorpay();

  @NestedConfigurationProperty
  private Stripe stripe = new Stripe();

  @NestedConfigurationProperty
  private Payu payu = new Payu();

  @NestedConfigurationProperty
  private Crypto crypto = new Crypto();

  /** Razorpay: HTTP Basic auth (keyId:keySecret), HMAC-SHA256 webhook signature. */
  @Data
  public static class Razorpay {
    private String keyId;
    private String keySecret;
    private String webhookSecret;
    private String baseUrl = "https://api.razorpay.com";
    /** Replay window for the webhook {@code created_at} field, in seconds (Node: 600). */
    private long replayWindowSeconds = 600;
  }

  /** Stripe: Bearer {secretKey}, HMAC-SHA256 over {@code {t}.{rawBody}} webhook signature. */
  @Data
  public static class Stripe {
    private String secretKey;
    private String publishableKey;
    private String webhookSecret;
    private String baseUrl = "https://api.stripe.com";
    /** Signature tolerance window in seconds (Node: 300). */
    private long toleranceSeconds = 300;
  }

  /** PayU: redirect/post flow, SHA-512 reverse-hash webhook verification (no API call). */
  @Data
  public static class Payu {
    private String merchantKey;
    private String merchantSalt;
    private String baseUrl = "https://secure.payu.in";
  }

  /**
   * Crypto (USDT-TRC20 / BTC): NON-CUSTODIAL — a single, fixed, merchant-owned receiving
   * address per asset (never derived/generated server-side; no private key ever touches this
   * service). Confirmation is detected by polling a PUBLIC block explorer API (no provider
   * webhook exists for a self-custodied wallet), so "verifyAndParseWebhook" is only ever
   * invoked internally by {@code CryptoChainPoller} with a synthetic, self-constructed event
   * — never from an external HTTP caller (there is no public crypto webhook endpoint).
   *
   * <p>Amount-tagging disambiguates concurrent orders paying the same address: each charge's
   * target amount gets a tiny deterministic offset derived from its order ref, and the poller
   * matches an on-chain transfer to a PENDING charge by (address, tagged amount, not-yet-consumed
   * txHash) rather than assuming one-payment-per-address.
   *
   * <p>⚠ VERIFY AT EXECUTION TIME: the TronGrid and mempool.space response shapes below are
   * implemented from their publicly documented conventions, not confirmed against a live call
   * from this environment (no network/API access during development) — see
   * {@code CryptoGateway} for where that risk is isolated.
   */
  @Data
  public static class Crypto {
    /** Merchant's own USDT-TRC20 (Tron) receiving address. Never generated by this service. */
    private String usdtTrc20Address;
    /** Merchant's own ETH-BEP20 (Binance-Peg Ethereum Token on BSC) receiving address. Never generated by this service. */
    private String ethBep20Address;
    /** Merchant's own BTC receiving address. Never generated by this service. */
    private String btcAddress;

    private String tronGridBaseUrl = "https://api.trongrid.io";
    /** USDT's official TRC20 contract address on Tron mainnet. */
    private String usdtTrc20ContractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";
    private String mempoolBaseUrl = "https://mempool.space/api";
    /** Public, keyless spot-price API used for the BTC/USD and ETH/USD rate at charge-creation time. */
    private String rateApiBaseUrl = "https://api.coingecko.com/api/v3";
    /**
     * Public, keyless BNB Smart Chain JSON-RPC endpoint used for ETH-BEP20 transfer detection
     * (eth_getLogs on the token's Transfer event — BSC is EVM-compatible, same JSON-RPC shape
     * as Ethereum) — no API key required, but public RPC reliability varies; swap for a
     * dedicated provider endpoint if this one proves flaky in production.
     */
    private String bscRpcUrl = "https://bsc-dataseed.binance.org";
    /** Binance-Peg Ethereum Token's official BEP20 contract address on BSC mainnet. */
    private String ethBep20ContractAddress = "0x2170Ed0880ac9A755fd29B2688956BD959F933F8";

    /** Confirmations required before a BTC payment is treated as settled. */
    private int btcConfirmationsRequired = 3;
    /** Confirmations required before a BEP20 (BSC) payment is treated as settled — BSC's ~3s
     *  block time means a given time window needs more confirmations than Ethereum/BTC. */
    private int bscConfirmationsRequired = 15;
    /** How long a generated deposit request stays open before it's treated as expired. */
    private long chargeExpiryMinutes = 60;
  }
}
