'use strict';
module.exports = (sequelize, DataTypes) =>
    sequelize.define('PodcastShow', {
        id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
        slug: { type: DataTypes.STRING(200), allowNull: false, unique: true },
        title: { type: DataTypes.STRING(200), allowNull: false },
        host: { type: DataTypes.STRING(300) },
        publisher: { type: DataTypes.STRING(200) },
        description: { type: DataTypes.TEXT, defaultValue: '' },
        category: { type: DataTypes.STRING(60) },
        country_code: { type: DataTypes.STRING(10) },
        language: { type: DataTypes.STRING(40) },
        listen_url: { type: DataTypes.TEXT },
        website_url: { type: DataTypes.TEXT },
        cover_url: { type: DataTypes.TEXT },
        cover_credit: { type: DataTypes.TEXT },
        rank: { type: DataTypes.INTEGER },
        ranking_note: { type: DataTypes.TEXT },
        overview: { type: DataTypes.TEXT, defaultValue: '' },
        first_aired: { type: DataTypes.STRING(20) },
        frequency: { type: DataTypes.STRING(80) },
        format: { type: DataTypes.TEXT },
        best_for: { type: DataTypes.TEXT },
        faq: { type: DataTypes.JSONB, defaultValue: [] },
        sources: { type: DataTypes.JSONB, defaultValue: [] },
        seo_title: { type: DataTypes.STRING(200) },
        seo_description: { type: DataTypes.STRING(320) },
        reviewed_at: { type: DataTypes.DATE },
        indexable: { type: DataTypes.BOOLEAN, defaultValue: false },
        listen_links: { type: DataTypes.JSONB, defaultValue: [] },
        hosts: { type: DataTypes.JSONB, defaultValue: [] },
        related_article_slugs: { type: DataTypes.JSONB, defaultValue: [] },
        videos: { type: DataTypes.JSONB, defaultValue: [] },
        episodes: { type: DataTypes.JSONB, defaultValue: [] },
        published: { type: DataTypes.BOOLEAN, defaultValue: false },
        archived: { type: DataTypes.BOOLEAN, defaultValue: false },
    }, { schema: 'legal', tableName: 'podcast_shows', underscored: true, timestamps: true });
