import { CountryConfig, BrandConfig } from "./types";

export const COUNTRIES_CONFIG: CountryConfig[] = [
  {
    code: "us",
    name: "United States",
    enabled: true,
    currency: "USD",
    symbol: "$",
    locale: "en-US",
    taxType: "SALES_TAX",
    taxRate: 8.5,
    fxRate: 1,
    messagingStrategy: "Email",
    pricingVisibility: "mixed",
    featuredCategories: ["w-bags", "wa-complications"],
    storeId: "8503a0f6-dab8-4bc5-ad3d-95e4414d0fc7",
  },
  {
    code: "uk",
    name: "United Kingdom",
    enabled: true,
    currency: "GBP",
    symbol: "£",
    locale: "en-GB",
    taxType: "VAT",
    taxRate: 20,
    fxRate: 0.79,
    messagingStrategy: "Concierge",
    pricingVisibility: "gated",
    featuredCategories: ["m-tailoring", "wa-complications"],
    storeId: "cc29c680-5525-4bf2-9f2c-257366f3938e",
  },
  {
    code: "ae",
    name: "United Arab Emirates",
    enabled: true,
    currency: "AED",
    symbol: "د.إ",
    locale: "ar-AE",
    taxType: "VAT",
    taxRate: 5,
    fxRate: 3.67,
    messagingStrategy: "WhatsApp",
    pricingVisibility: "gated",
    featuredCategories: ["j-high", "w-bags"],
    storeId: "ef0b7c01-5a4b-47e2-975d-bfc6456c44a9",
  },
  {
    code: "in",
    name: "India",
    enabled: true,
    currency: "INR",
    symbol: "₹",
    locale: "en-IN",
    taxType: "GST",
    taxRate: 18,
    fxRate: 83.3,
    messagingStrategy: "WhatsApp",
    pricingVisibility: "public",
    featuredCategories: ["j-high", "m-tailoring"],
    storeId: "73e19cce-2841-4d22-9ed9-d9d46bd1af78",
  },
  {
    code: "sg",
    name: "Singapore",
    enabled: true,
    currency: "SGD",
    symbol: "S$",
    locale: "en-SG",
    taxType: "GST",
    taxRate: 7,
    fxRate: 1.35,
    messagingStrategy: "Concierge",
    pricingVisibility: "mixed",
    featuredCategories: ["wa-complications", "w-bags"],
    storeId: "6703b393-3215-4f0f-90e7-d509df5b173f",
  },
];

export const BRANDS_CONFIG: BrandConfig[] = [
  {
    id: "amarise-luxe",
    name: "AMARISÉ MAISON AVENUE",
    domain: "amarise-maison-avenue.com",
    theme: {
      primary: "#000000",
      secondary: "#FAF9F6",
      accent: "#D4AF37",
    },
    enabled: true,
  },
  {
    id: "future-maison-1",
    name: "L’ATELIER D’OR",
    domain: "latelier-dor.com",
    theme: {
      primary: "#1A1A1A",
      secondary: "#FFFFFF",
      accent: "#C5A059",
    },
    enabled: false,
  },
];
