-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.abuse_logs DROP CONSTRAINT IF EXISTS abuse_logs_org_id_fkey;

ALTER TABLE IF EXISTS public.abuse_logs DROP CONSTRAINT IF EXISTS abuse_logs_user_id_fkey;

ALTER TABLE IF EXISTS public.api_keys DROP CONSTRAINT IF EXISTS api_keys_created_by_fkey;

ALTER TABLE IF EXISTS public.api_keys DROP CONSTRAINT IF EXISTS api_keys_org_id_fkey;

ALTER TABLE IF EXISTS public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_admin_id_fkey;

ALTER TABLE IF EXISTS public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_org_id_fkey;

ALTER TABLE IF EXISTS public.chargebacks DROP CONSTRAINT IF EXISTS chargebacks_transaction_id_fkey;

ALTER TABLE IF EXISTS public.invoices DROP CONSTRAINT IF EXISTS invoices_org_id_fkey;

ALTER TABLE IF EXISTS public.invoices DROP CONSTRAINT IF EXISTS invoices_subscription_id_fkey;

ALTER TABLE IF EXISTS public.invoices DROP CONSTRAINT IF EXISTS invoices_user_id_fkey;

ALTER TABLE IF EXISTS public.notifications DROP CONSTRAINT IF EXISTS notifications_org_id_fkey;

ALTER TABLE IF EXISTS public.org_memberships DROP CONSTRAINT IF EXISTS org_memberships_invited_by_fkey;

ALTER TABLE IF EXISTS public.org_memberships DROP CONSTRAINT IF EXISTS org_memberships_org_id_fkey;

ALTER TABLE IF EXISTS public.org_memberships DROP CONSTRAINT IF EXISTS org_memberships_user_id_fkey;

ALTER TABLE IF EXISTS public.payment_methods DROP CONSTRAINT IF EXISTS payment_methods_org_id_fkey;

ALTER TABLE IF EXISTS public.payment_methods DROP CONSTRAINT IF EXISTS payment_methods_user_id_fkey;

ALTER TABLE IF EXISTS public.provider_health DROP CONSTRAINT IF EXISTS provider_health_provider_id_fkey;

ALTER TABLE IF EXISTS public.provider_incidents DROP CONSTRAINT IF EXISTS provider_incidents_provider_id_fkey;

ALTER TABLE IF EXISTS public.proxies DROP CONSTRAINT IF EXISTS proxies_org_id_fkey;

ALTER TABLE IF EXISTS public.proxies DROP CONSTRAINT IF EXISTS proxies_provider_id_fkey;

ALTER TABLE IF EXISTS public.proxy_usage_logs DROP CONSTRAINT IF EXISTS proxy_usage_logs_org_id_fkey;

ALTER TABLE IF EXISTS public.proxy_usage_logs DROP CONSTRAINT IF EXISTS proxy_usage_logs_proxy_id_fkey;

ALTER TABLE IF EXISTS public.proxy_usage_logs DROP CONSTRAINT IF EXISTS proxy_usage_logs_user_id_fkey;

ALTER TABLE IF EXISTS public.refresh_tokens DROP CONSTRAINT IF EXISTS refresh_tokens_org_id_fkey;

ALTER TABLE IF EXISTS public.refresh_tokens DROP CONSTRAINT IF EXISTS refresh_tokens_user_id_fkey;

ALTER TABLE IF EXISTS public.routing_rules DROP CONSTRAINT IF EXISTS routing_rules_provider_id_fkey;

ALTER TABLE IF EXISTS public.sessions DROP CONSTRAINT IF EXISTS sessions_org_id_fkey;

ALTER TABLE IF EXISTS public.sessions DROP CONSTRAINT IF EXISTS sessions_user_id_fkey;

ALTER TABLE IF EXISTS public.sub_users DROP CONSTRAINT IF EXISTS sub_users_org_id_fkey;

ALTER TABLE IF EXISTS public.sub_users DROP CONSTRAINT IF EXISTS sub_users_parent_user_id_fkey;

ALTER TABLE IF EXISTS public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_org_id_fkey;

ALTER TABLE IF EXISTS public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_plan_id_fkey;

ALTER TABLE IF EXISTS public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_user_id_fkey;

ALTER TABLE IF EXISTS public.support_tickets DROP CONSTRAINT IF EXISTS support_tickets_org_id_fkey;

ALTER TABLE IF EXISTS public.ticket_messages DROP CONSTRAINT IF EXISTS ticket_messages_author_user_id_fkey;

ALTER TABLE IF EXISTS public.ticket_messages DROP CONSTRAINT IF EXISTS ticket_messages_org_id_fkey;

ALTER TABLE IF EXISTS public.ticket_messages DROP CONSTRAINT IF EXISTS ticket_messages_ticket_id_fkey;

ALTER TABLE IF EXISTS public.transactions DROP CONSTRAINT IF EXISTS transactions_org_id_fkey;

ALTER TABLE IF EXISTS public.transactions DROP CONSTRAINT IF EXISTS transactions_user_id_fkey;

ALTER TABLE IF EXISTS public.usage_records DROP CONSTRAINT IF EXISTS usage_records_org_id_fkey;

ALTER TABLE IF EXISTS public.users DROP CONSTRAINT IF EXISTS users_org_id_fkey;

ALTER TABLE IF EXISTS public.users DROP CONSTRAINT IF EXISTS users_plan_id_fkey;



DROP TABLE IF EXISTS public.abuse_logs;

CREATE TABLE IF NOT EXISTS public.abuse_logs
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    event_type character varying(60) COLLATE pg_catalog."default" NOT NULL,
    risk_score numeric(5, 2) NOT NULL,
    action_taken character varying(60) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT abuse_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.abuse_logs
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.api_keys;

CREATE TABLE IF NOT EXISTS public.api_keys
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    key_prefix text COLLATE pg_catalog."default" NOT NULL,
    key_hash text COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.api_keys
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.audit_logs;

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id bigserial NOT NULL,
    admin_id bigint NOT NULL,
    action character varying(120) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(80) COLLATE pg_catalog."default" NOT NULL,
    entity_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.audit_logs
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.chargebacks;

CREATE TABLE IF NOT EXISTS public.chargebacks
(
    id bigserial NOT NULL,
    transaction_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    evidence_submitted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chargebacks_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.feature_flags;

CREATE TABLE IF NOT EXISTS public.feature_flags
(
    key text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    default_value boolean NOT NULL DEFAULT false,
    plans jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT feature_flags_pkey PRIMARY KEY (key)
);

DROP TABLE IF EXISTS public.invoices;

CREATE TABLE IF NOT EXISTS public.invoices
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    amount numeric(12, 2) NOT NULL,
    tax numeric(12, 2) NOT NULL DEFAULT 0,
    total numeric(12, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    issued_at timestamp without time zone NOT NULL,
    due_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.invoices
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.notifications;

CREATE TABLE IF NOT EXISTS public.notifications
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.notifications
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.org_memberships;

CREATE TABLE IF NOT EXISTS public.org_memberships
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    user_id bigint NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    invited_by bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT org_memberships_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.org_memberships
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.organizations;

CREATE TABLE IF NOT EXISTS public.organizations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    slug text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    plan_slug text COLLATE pg_catalog."default" NOT NULL DEFAULT 'starter'::text,
    bandwidth_limit_gb bigint NOT NULL DEFAULT 0,
    bandwidth_used_gb bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT organizations_pkey PRIMARY KEY (id),
    CONSTRAINT organizations_slug_key UNIQUE (slug)
);

ALTER TABLE IF EXISTS public.organizations
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.payment_methods;

CREATE TABLE IF NOT EXISTS public.payment_methods
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    gateway character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last4 character(4) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(30) COLLATE pg_catalog."default" NOT NULL,
    expiry character varying(12) COLLATE pg_catalog."default" NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.payment_methods
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.plans;

CREATE TABLE IF NOT EXISTS public.plans
(
    id bigserial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    price numeric(12, 2) NOT NULL,
    bandwidth_limit bigint NOT NULL,
    proxy_types_allowed jsonb NOT NULL DEFAULT '[]'::jsonb,
    overage_price numeric(12, 4) NOT NULL DEFAULT 0,
    session_limits integer NOT NULL DEFAULT 0,
    rotation_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT plans_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.provider_health;

CREATE TABLE IF NOT EXISTS public.provider_health
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    provider_id bigint NOT NULL,
    latency_ms integer NOT NULL DEFAULT 0,
    success_rate numeric(5, 2) NOT NULL DEFAULT 0,
    status text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT provider_health_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.provider_incidents;

CREATE TABLE IF NOT EXISTS public.provider_incidents
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    provider_id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::text,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT provider_incidents_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.providers;

CREATE TABLE IF NOT EXISTS public.providers
(
    id bigserial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    priority integer NOT NULL DEFAULT 1,
    failover_enabled boolean NOT NULL DEFAULT true,
    health_score numeric(5, 2) NOT NULL DEFAULT 100,
    countries_supported jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT providers_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.proxies;

CREATE TABLE IF NOT EXISTS public.proxies
(
    id bigserial NOT NULL,
    provider_id bigint NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ip inet NOT NULL,
    port integer NOT NULL,
    country character(2) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    success_rate numeric(5, 2) NOT NULL DEFAULT 100,
    latency integer NOT NULL DEFAULT 0,
    bandwidth_limit bigint NOT NULL DEFAULT 0,
    bandwidth_used bigint NOT NULL DEFAULT 0,
    health_score numeric(5, 2) NOT NULL DEFAULT 100,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT proxies_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.proxies
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.proxy_usage_logs;

CREATE TABLE IF NOT EXISTS public.proxy_usage_logs
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    proxy_id bigint NOT NULL,
    bandwidth_used bigint NOT NULL,
    success boolean NOT NULL,
    response_time integer NOT NULL,
    "timestamp" timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT proxy_usage_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.proxy_usage_logs
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.refresh_tokens;

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.refresh_tokens
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.routing_rules;

CREATE TABLE IF NOT EXISTS public.routing_rules
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    priority integer NOT NULL DEFAULT 1,
    name text COLLATE pg_catalog."default" NOT NULL,
    match jsonb NOT NULL DEFAULT '{}'::jsonb,
    provider_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT routing_rules_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.sessions;

CREATE TABLE IF NOT EXISTS public.sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    user_id bigint NOT NULL,
    refresh_token_hash text COLLATE pg_catalog."default" NOT NULL,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.sessions
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.sub_users;

CREATE TABLE IF NOT EXISTS public.sub_users
(
    id bigserial NOT NULL,
    parent_user_id bigint NOT NULL,
    gb_limit numeric(12, 2) NOT NULL DEFAULT 0,
    usage_gb numeric(12, 2) NOT NULL DEFAULT 0,
    status character varying(16) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT sub_users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.sub_users
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.subscriptions;

CREATE TABLE IF NOT EXISTS public.subscriptions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    current_period_start timestamp without time zone NOT NULL,
    current_period_end timestamp without time zone NOT NULL,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    grace_until timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.subscriptions
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.support_tickets;

CREATE TABLE IF NOT EXISTS public.support_tickets
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    subject text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::text,
    priority text COLLATE pg_catalog."default" NOT NULL DEFAULT 'normal'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT support_tickets_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.support_tickets
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.system_incidents;

CREATE TABLE IF NOT EXISTS public.system_incidents
(
    id bigserial NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp without time zone NOT NULL,
    resolved_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT system_incidents_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.ticket_messages;

CREATE TABLE IF NOT EXISTS public.ticket_messages
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    ticket_id uuid NOT NULL,
    author_user_id bigint,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_messages_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.ticket_messages
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.transactions;

CREATE TABLE IF NOT EXISTS public.transactions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    gateway character varying(30) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    currency character(3) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    risk_score numeric(5, 2) NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    gateway_order_id character varying COLLATE pg_catalog."default",
    org_id uuid NOT NULL,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.transactions
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.usage_records;

CREATE TABLE IF NOT EXISTS public.usage_records
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    bandwidth_gb numeric(12, 2) NOT NULL DEFAULT 0,
    requests bigint NOT NULL DEFAULT 0,
    success_rate numeric(5, 2) NOT NULL DEFAULT 0,
    avg_latency_ms integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT usage_records_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.usage_records
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(32) COLLATE pg_catalog."default" NOT NULL,
    status character varying(16) COLLATE pg_catalog."default" NOT NULL,
    plan_id bigint,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    org_id uuid NOT NULL,
    full_name text COLLATE pg_catalog."default",
    mfa_enabled boolean NOT NULL DEFAULT false,
    mfa_secret text COLLATE pg_catalog."default",
    email_verified_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.users
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.webhook_logs;

CREATE TABLE IF NOT EXISTS public.webhook_logs
(
    id bigserial NOT NULL,
    gateway character varying(30) COLLATE pg_catalog."default" NOT NULL,
    payload_json jsonb NOT NULL,
    signature_verified boolean NOT NULL,
    processed boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT webhook_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.abuse_logs
    ADD CONSTRAINT abuse_logs_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_abuse_logs_org_id
    ON public.abuse_logs(org_id);


ALTER TABLE IF EXISTS public.abuse_logs
    ADD CONSTRAINT abuse_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_api_keys_org_id
    ON public.api_keys(org_id);


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_audit_logs_org_id
    ON public.audit_logs(org_id);


ALTER TABLE IF EXISTS public.chargebacks
    ADD CONSTRAINT chargebacks_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_invoices_org_id
    ON public.invoices(org_id);


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_subscription_id_fkey FOREIGN KEY (subscription_id)
    REFERENCES public.subscriptions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_org_id
    ON public.notifications(org_id);


ALTER TABLE IF EXISTS public.org_memberships
    ADD CONSTRAINT org_memberships_invited_by_fkey FOREIGN KEY (invited_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.org_memberships
    ADD CONSTRAINT org_memberships_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_org_memberships_org_id
    ON public.org_memberships(org_id);


ALTER TABLE IF EXISTS public.org_memberships
    ADD CONSTRAINT org_memberships_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payment_methods
    ADD CONSTRAINT payment_methods_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_payment_methods_org_id
    ON public.payment_methods(org_id);


ALTER TABLE IF EXISTS public.payment_methods
    ADD CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_health
    ADD CONSTRAINT provider_health_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider_incidents
    ADD CONSTRAINT provider_incidents_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.proxies
    ADD CONSTRAINT proxies_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_proxies_org_id
    ON public.proxies(org_id);


ALTER TABLE IF EXISTS public.proxies
    ADD CONSTRAINT proxies_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proxy_usage_logs
    ADD CONSTRAINT proxy_usage_logs_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_proxy_usage_logs_org_id
    ON public.proxy_usage_logs(org_id);


ALTER TABLE IF EXISTS public.proxy_usage_logs
    ADD CONSTRAINT proxy_usage_logs_proxy_id_fkey FOREIGN KEY (proxy_id)
    REFERENCES public.proxies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proxy_usage_logs
    ADD CONSTRAINT proxy_usage_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_org_id
    ON public.refresh_tokens(org_id);


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.routing_rules
    ADD CONSTRAINT routing_rules_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_org_id
    ON public.sessions(org_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sub_users
    ADD CONSTRAINT sub_users_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sub_users_org_id
    ON public.sub_users(org_id);


ALTER TABLE IF EXISTS public.sub_users
    ADD CONSTRAINT sub_users_parent_user_id_fkey FOREIGN KEY (parent_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_subscriptions_org_id
    ON public.subscriptions(org_id);


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.support_tickets
    ADD CONSTRAINT support_tickets_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_support_tickets_org_id
    ON public.support_tickets(org_id);


ALTER TABLE IF EXISTS public.ticket_messages
    ADD CONSTRAINT ticket_messages_author_user_id_fkey FOREIGN KEY (author_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_messages
    ADD CONSTRAINT ticket_messages_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ticket_messages_org_id
    ON public.ticket_messages(org_id);


ALTER TABLE IF EXISTS public.ticket_messages
    ADD CONSTRAINT ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES public.support_tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_transactions_org_id
    ON public.transactions(org_id);


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usage_records
    ADD CONSTRAINT usage_records_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_usage_records_org_id
    ON public.usage_records(org_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_users_org_id
    ON public.users(org_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;