export interface ForumAuthor {
  username: string;
  avatarColor: string;
  avatarLetter: string;
  rank: string;
  rankColor: string;
  joinDate: string;
  messagesCount: number;
  reactionScore: number;
  isOnline: boolean;
}

export interface ForumReplyItem {
  pid: string;
  postNumber: number;
  author: ForumAuthor;
  date: string;
  content: string;
  quote?: { author: string; text: string };
  likes: number;
}

export interface ForumThreadItem {
  tid: string;
  subforumSlug: string;
  title: string;
  prefix: string;
  prefixColor: string; // e.g. "red", "green", "blue", "gold", "purple"
  isPinned?: boolean;
  author: ForumAuthor;
  date: string;
  views: number;
  replies: number;
  originalPost: {
    content: string;
    signature?: string;
  };
  posts: ForumReplyItem[];
}

export interface ForumSubNode {
  slug: string;
  name: string;
  description: string;
  subLink?: { title: string; href: string };
  iconType: "cash" | "chat" | "ebay" | "bitcoin" | "freelancer" | "cursor" | "youtube" | "udemy" | "server" | "shield" | "gamepad" | "exchange" | "crosshair" | "lock" | "eye-off" | "globe" | "key" | "megaphone" | "newspaper" | "users" | "smile";
  threadsCount: string;
  messagesCount: string;
  latestPost: {
    title: string;
    tag?: string;
    author: string;
    authorInitial: string;
    avatarColor: string;
    timestamp: string;
    tid: string;
  };
}

export interface ForumCategory {
  slug: string;
  title: string;
  numericId?: string;
  subNodes: ForumSubNode[];
}

export const FORUM_CATEGORIES: ForumCategory[] = [
  {
    slug: "home",
    title: "Home",
    numericId: "15",
    subNodes: [
      {
        slug: "announcements",
        name: "Announcements",
        description: "Get the scoop on what is happening at Altenen.",
        iconType: "megaphone",
        threadsCount: "45",
        messagesCount: "3K",
        latestPost: {
          title: "Happy New Year ATN",
          author: "JulisJay",
          authorInitial: "J",
          avatarColor: "#cc3399",
          timestamp: "Sep 28, 2025",
          tid: "happy-new-year",
        },
      },
      {
        slug: "comments-feedbacks",
        name: "Comments & FeedBacks",
        description: "Give comments and feedback about Altenen in this section. Suggest for new stuff like sections, usergroups etc.",
        iconType: "chat",
        threadsCount: "243",
        messagesCount: "2.1K",
        latestPost: {
          title: "VIP Members Feedbacks",
          author: "Shantaram90",
          authorInitial: "S",
          avatarColor: "#999933",
          timestamp: "Yesterday at 9:40 AM",
          tid: "vip-feedbacks",
        },
      },
      {
        slug: "applications-rank-award",
        name: "Applications Rank/Award",
        description: "Apply for Ranks or Awards in this section.",
        iconType: "users",
        threadsCount: "818",
        messagesCount: "3.2K",
        latestPost: {
          title: "Request Top Carder Rank",
          author: "likewise01",
          authorInitial: "L",
          avatarColor: "#2980b9",
          timestamp: "Sep 15, 2026",
          tid: "request-top-carder",
        },
      },
      {
        slug: "technical-support",
        name: "Technical Support",
        description: "Bugs, problems & related",
        iconType: "server",
        threadsCount: "1.6K",
        messagesCount: "4.9K",
        latestPost: {
          title: "How to fix login loop error",
          author: "mrzsleek",
          authorInitial: "M",
          avatarColor: "#3333cc",
          timestamp: "Today at 10:20 AM",
          tid: "login-loop-error",
        },
      },
    ],
  },
  {
    slug: "community",
    title: "Community",
    numericId: "27",
    subNodes: [
      {
        slug: "general-discussion",
        name: "General Discussion",
        description: "Talk About what ever you want here, try not to spam.",
        iconType: "chat",
        threadsCount: "8.8K",
        messagesCount: "34.8K",
        latestPost: {
          title: "FREE CC checker ( all crédit card )",
          author: "eslam960",
          authorInitial: "E",
          avatarColor: "#66cc33",
          timestamp: "Today at 7:02 AM",
          tid: "free-cc-checker",
        },
      },
      {
        slug: "hello-world",
        name: "Hello World!",
        description: "Introduce yourself to other members.",
        iconType: "smile",
        threadsCount: "229.1K",
        messagesCount: "257.8K",
        latestPost: {
          title: "Post thread | Altenens | Elite Underground",
          tag: "Hello",
          author: "Ali2013",
          authorInitial: "A",
          avatarColor: "#33cc66",
          timestamp: "Yesterday at 1:16 PM",
          tid: "introduce-yourself",
        },
      },
      {
        slug: "international-no-english",
        name: "International - No English",
        description: "Speak your language here.",
        iconType: "globe",
        threadsCount: "1.3K",
        messagesCount: "6.7K",
        latestPost: {
          title: "[Money-فلوس🤑] افضل طريقة تطلع منها فلوس بالحلال",
          author: "mrrx8000",
          authorInitial: "M",
          avatarColor: "#141452",
          timestamp: "Today at 9:00 AM",
          tid: "best-way-halal-money",
        },
      },
      {
        slug: "technology-finance-news",
        name: "Technology & Finance News",
        description: "Find the latest business news pertaining to Technology covering companies, advancements, multimedia, electronics, mobile technologies, and science at Altenen.",
        iconType: "newspaper",
        threadsCount: "174",
        messagesCount: "1.3K",
        latestPost: {
          title: "MAKE EASY MONEY NOW 5K PER WEEK",
          author: "Poopandpee321",
          authorInitial: "P",
          avatarColor: "#c2f0c2",
          timestamp: "Today at 7:18 AM",
          tid: "easy-money-5k",
        },
      },
      {
        slug: "comedy",
        name: "Comedy",
        description: "This Section professional entertainment consisting of jokes and satirical sketches, intended to make an audience laugh,Lets put something funny on ATN.",
        iconType: "smile",
        threadsCount: "97",
        messagesCount: "674",
        latestPost: {
          title: "Discover Free Money-Making Tutorials!",
          author: "Kimx91",
          authorInitial: "K",
          avatarColor: "#333399",
          timestamp: "Sep 12, 2026",
          tid: "discover-free-money",
        },
      },
    ],
  },
  {
    slug: "server-infrastructure",
    title: "Server & Infrastructure",
    subNodes: [
      {
        slug: "vps-rdp",
        name: "VPS/RDP",
        description: "Get free RDP accounts and free VPS accounts and also much methods to get free VPS and RDP accounts.",
        iconType: "server",
        threadsCount: "1.3K",
        messagesCount: "167.6K",
        latestPost: {
          title: "GET RDP / VPS FOR FREE 100% WORKING METHOD",
          tag: "TUTORIAL",
          author: "morenoaliaj",
          authorInitial: "M",
          avatarColor: "#8e44ad",
          timestamp: "Today at 5:39 AM",
          tid: "vps-rdp-guide-2026",
        },
      },
      {
        slug: "vpn",
        name: "VPN",
        description: "Talk about VPN stuff, Share Free VPN accounts with Altenen community.",
        iconType: "shield",
        threadsCount: "9.1K",
        messagesCount: "347.4K",
        latestPost: {
          title: "5 PUREVPN ACCOUNTS WITH 2 YEARS PREMIUM",
          tag: "VPN",
          author: "mogard88",
          authorInitial: "M",
          avatarColor: "#27ae60",
          timestamp: "Today at 1:09 AM",
          tid: "vpn-accounts-premium-2026",
        },
      },
    ],
  },
  {
    slug: "making-money-and-courses",
    title: "Making Money and Courses",
    numericId: "469147",
    subNodes: [
      {
        slug: "earnings-schemes",
        name: "Earnings schemes",
        description: "Discuss different ways to monetize your websites and other ways to make money online.",
        subLink: {
          title: "Referral Link Section For Make Money",
          href: "/forum/earnings-schemes?filter=referral",
        },
        iconType: "cash",
        threadsCount: "6.4K",
        messagesCount: "267.6K",
        latestPost: {
          title: "[VIP METHOD] $3K+/Month with Automated Micro-SaaS & Affiliate Flow",
          tag: "VIP METHOD",
          author: "altoooi",
          authorInitial: "A",
          avatarColor: "#c0392b",
          timestamp: "36 minutes ago",
          tid: "vip-method-3k-month",
        },
      },
      {
        slug: "thelifehack",
        name: "TheLifehack",
        description: "Lifehack (or life-hacking) is any trick, shortcut, skill, it's dedicated to making life as easy and convenient as possible by showing you all the essential ingredients of productivity . The topics covered are almost endless; they include money, relationship, lifestyle, psychology, parenting, tech, and more. Everything on TheLifehack.",
        iconType: "chat",
        threadsCount: "408",
        messagesCount: "32.8K",
        latestPost: {
          title: "☆ Here are 3 high quality voice clone workflows for productivity",
          tag: "LIFEHACK",
          author: "Ssczedward",
          authorInitial: "S",
          avatarColor: "#8e44ad",
          timestamp: "Yesterday at 7:46 PM",
          tid: "lifehack-voice-productivity",
        },
      },
      {
        slug: "ebay",
        name: "Ebay",
        description: "Discuss all of your Ebay auction tactics here.",
        iconType: "ebay",
        threadsCount: "81",
        messagesCount: "11.9K",
        latestPost: {
          title: "⚡ X30 EBAY SELLER OPTIMIZATION SECRETS FOR 2026",
          tag: "GUIDE",
          author: "Djagerrr",
          authorInitial: "D",
          avatarColor: "#d35400",
          timestamp: "Yesterday at 10:28 PM",
          tid: "ebay-optimization-secrets",
        },
      },
      {
        slug: "cryptocurrency",
        name: "CryptoCurrency",
        description: "Discuss all CryptoCurrencies / coins and their use within the Making Money Niche. Bitcoin is possibly the best known but there are numerous crypto currencies, this is the forum to discuss them all.",
        iconType: "bitcoin",
        threadsCount: "3.4K",
        messagesCount: "64.2K",
        latestPost: {
          title: "500$ usdt Code Free Crypto Quiz Bonus Rewards",
          tag: "AIRDROP",
          author: "Blackface54",
          authorInitial: "B",
          avatarColor: "#2980b9",
          timestamp: "9 minutes ago",
          tid: "crypto-quiz-rewards-500",
        },
      },
      {
        slug: "hire-a-freelancer",
        name: "Hire a Freelancer",
        description: "Want to hire a freelancer to build a bot, complete a task, or something else? Post your 'Hire A Freelancer' (HAF) threads here. Please do not confuse this section with the Want To Buy section!",
        iconType: "freelancer",
        threadsCount: "711",
        messagesCount: "4K",
        latestPost: {
          title: "[HIRING] Looking for Fullstack Developer for custom dashboard",
          tag: "HIRING",
          author: "Luffa",
          authorInitial: "L",
          avatarColor: "#27ae60",
          timestamp: "Yesterday at 3:39 PM",
          tid: "hiring-fullstack-dashboard",
        },
      },
      {
        slug: "pay-per-click",
        name: "Pay Per Click",
        description: "Discuss all of your Pay Per Click tactics to increase quality scores, conversions, and more using Adwords, Facebook Ads, Bing Ads, and other PPC networks here.",
        iconType: "cursor",
        threadsCount: "499",
        messagesCount: "39.4K",
        latestPost: {
          title: "Get paid for viewing short videos - PPC arbitrage blueprint",
          tag: "PPC",
          author: "CrySS",
          authorInitial: "C",
          avatarColor: "#7f8c8d",
          timestamp: "Today at 1:00 AM",
          tid: "ppc-arbitrage-blueprint",
        },
      },
      {
        slug: "youtube",
        name: "YouTube",
        description: "Discuss your ideas and methods to increase views, video engagement, and revenue from YouTube using ads or your own products and service.",
        iconType: "youtube",
        threadsCount: "205",
        messagesCount: "33.6K",
        latestPost: {
          title: "🔥 Increase Subscribes Views Likes with new algorithm prompt loop",
          tag: "YOUTUBE",
          author: "hdmovie8",
          authorInitial: "H",
          avatarColor: "#c0392b",
          timestamp: "Wednesday at 2:51 PM",
          tid: "youtube-algorithm-growth",
        },
      },
      {
        slug: "udemy-courses",
        name: "Udemy Courses",
        description: "Udemy Paid Courses for Learning Hacking , Programing , Learning languages , Business , Earn Money , Online Shopping , Android , Web , Python , Seo , Social Media Marketing",
        iconType: "udemy",
        threadsCount: "1.2K",
        messagesCount: "55.9K",
        latestPost: {
          title: "[UDEMY] 1120+ PAID COURSES 100% OFF COUPONS PACK [UPDATED]",
          tag: "UDEMY",
          author: "ddoser",
          authorInitial: "D",
          avatarColor: "#9c27b0",
          timestamp: "Today at 2:48 AM",
          tid: "udemy-1120-courses-pack",
        },
      },
    ],
  },
  {
    slug: "anonymity-section",
    title: "Anonymity Section",
    numericId: "31",
    subNodes: [
      {
        slug: "vpn-and-proxies",
        name: "VPN & SOCKS5 Proxies",
        description: "Discussions, setups, and recommendations for WireGuard, OpenVPN, residential proxies, and traffic tunneling.",
        iconType: "shield",
        threadsCount: "5.8K",
        messagesCount: "184.2K",
        latestPost: {
          title: "[GUIDE] Setting up a private WireGuard node with DNS leak protection",
          tag: "GUIDE",
          author: "GhostNet",
          authorInitial: "G",
          avatarColor: "#27ae60",
          timestamp: "22 minutes ago",
          tid: "wireguard-private-node-guide",
        },
      },
      {
        slug: "tor-and-i2p",
        name: "Tor and I2P Networks",
        description: "Onion routing, hidden services setup, bridges, obfs4 transport, and Tails OS hardening.",
        iconType: "globe",
        threadsCount: "1.4K",
        messagesCount: "42.1K",
        latestPost: {
          title: "[RESOURCE] Recommended Tor Bridges & Obfs4 configuration for 2026",
          tag: "RESOURCE",
          author: "CipherPunk",
          authorInitial: "C",
          avatarColor: "#8e44ad",
          timestamp: "Today at 11:15 AM",
          tid: "tor-bridges-obfs4-2026",
        },
      },
      {
        slug: "antidetect-browsers",
        name: "Anti-Detect Browsers & Fingerprinting",
        description: "Techniques and tools for managing browser fingerprints, Canvas/WebGL isolation, WebRTC leaks, and user-agent profiles.",
        iconType: "eye-off",
        threadsCount: "2.9K",
        messagesCount: "98.6K",
        latestPost: {
          title: "[ANALYSIS] Canvas and audio fingerprint evasion comparison across browsers",
          tag: "ANALYSIS",
          author: "SilentNode",
          authorInitial: "S",
          avatarColor: "#2980b9",
          timestamp: "Today at 8:40 AM",
          tid: "canvas-fingerprint-evasion",
        },
      },
      {
        slug: "opsec-privacy-guides",
        name: "OpSec & Digital Privacy",
        description: "Operational security, hardened operating systems (Qubes, Tails), PGP key management, disk encryption, and metadata scrubbing.",
        iconType: "lock",
        threadsCount: "3.1K",
        messagesCount: "76.5K",
        latestPost: {
          title: "[VIP METHOD] Complete Operational Security checklist for independent researchers",
          tag: "VIP METHOD",
          author: "NullPointer",
          authorInitial: "N",
          avatarColor: "#c0392b",
          timestamp: "Yesterday at 4:20 PM",
          tid: "opsec-checklist-researchers",
        },
      },
    ],
  },
  {
    slug: "gaming-zone",
    title: "Gaming Zone",
    subNodes: [
      {
        slug: "general-games",
        name: "General Games Discussion",
        description: "Talk About what ever you want About Games Here, try not to spam.",
        iconType: "gamepad",
        threadsCount: "1.7K",
        messagesCount: "22.8K",
        latestPost: {
          title: "\\587X SUPERCELL FA...",
          tag: "GAMING",
          author: "snapshot",
          authorInitial: "S",
          avatarColor: "#8e44ad",
          timestamp: "Today at 12:48 AM",
          tid: "gaming-supercell-discussion",
        },
      },
      {
        slug: "trading-games",
        name: "Trading Games",
        description: "Trade Any Game in this Section, Please try to Not Spam",
        iconType: "exchange",
        threadsCount: "100",
        messagesCount: "2.2K",
        latestPost: {
          title: "quiero todooo",
          author: "123331exz",
          authorInitial: "1",
          avatarColor: "#f39c12",
          timestamp: "Wednesday at 3:38 AM",
          tid: "trading-steam-keys",
        },
      },
      {
        slug: "csgo",
        name: "CS:GO {Counter-Strike}",
        description: "Everything About CS:GO Can Be Found here",
        iconType: "crosshair",
        threadsCount: "525",
        messagesCount: "14.9K",
        latestPost: {
          title: "Get free money and free...",
          tag: "GAMING",
          author: "forfreeaa",
          authorInitial: "F",
          avatarColor: "#34495e",
          timestamp: "Yesterday at 3:14 PM",
          tid: "csgo-tactics-2026",
        },
      },
    ],
  },
];

// Prepopulated thread database with rich XenForo format
export const INITIAL_THREADS: ForumThreadItem[] = [
  {
    tid: "vip-method-3k-month",
    subforumSlug: "earnings-schemes",
    title: "[VIP METHOD] $3K+/Month with Automated Micro-SaaS & Affiliate Flow",
    prefix: "VIP METHOD",
    prefixColor: "red",
    isPinned: true,
    author: {
      username: "altoooi",
      avatarColor: "#c0392b",
      avatarLetter: "A",
      rank: "VIP MEMBER",
      rankColor: "#e74c3c",
      joinDate: "Jan 14, 2022",
      messagesCount: 1428,
      reactionScore: 894,
      isOnline: true,
    },
    date: "Today at 4:12 AM",
    views: 4892,
    replies: 4,
    originalPost: {
      content: `Hello members,\n\nIn this thread, I am sharing the updated breakdown of how we set up automated affiliate review portals that consistently produce over $3,000 net monthly profit with zero inventory and minimal maintenance.\n\n### Core Architecture:\n1. **Cloudflare Workers / Edge Routing**: Ultra-fast latency routing for product comparison matrices.\n2. **Targeted SEO Long-tail Keywords**: Ranking for high-intent queries (e.g., "Best developer infrastructure tools for scale").\n3. **Real-time Conversion Webhooks**: Immediate payout tracking and split testing.\n\nAll tools used in this stack are 100% compliant with standard ad networks. Leave a reply below if you want the sample configuration JSON!`,
      signature: "⚡ Knowledge is freedom — Trade with discipline.",
    },
    posts: [
      {
        pid: "post-101",
        postNumber: 2,
        author: {
          username: "DarkViper",
          avatarColor: "#2980b9",
          avatarLetter: "D",
          rank: "SENIOR MEMBER",
          rankColor: "#3498db",
          joinDate: "Mar 2023",
          messagesCount: 612,
          reactionScore: 430,
          isOnline: true,
        },
        date: "Today at 4:45 AM",
        content: "Awesome guide @altoooi! Did you use Next.js for the dynamic landing pages or raw Astro static site generator? Thanks for sharing this VIP method.",
        likes: 12,
      },
      {
        pid: "post-102",
        postNumber: 3,
        author: {
          username: "altoooi",
          avatarColor: "#c0392b",
          avatarLetter: "A",
          rank: "VIP MEMBER",
          rankColor: "#e74c3c",
          joinDate: "Jan 14, 2022",
          messagesCount: 1428,
          reactionScore: 894,
          isOnline: true,
        },
        date: "Today at 5:10 AM",
        quote: {
          author: "DarkViper",
          text: "Did you use Next.js for the dynamic landing pages or raw Astro static site generator?",
        },
        content: "We use Next.js with incremental static regeneration (ISR). Gives you the speed of static HTML with automatic re-validation whenever pricing or affiliate tags change.",
        likes: 19,
      },
      {
        pid: "post-103",
        postNumber: 4,
        author: {
          username: "NexusCoder",
          avatarColor: "#27ae60",
          avatarLetter: "N",
          rank: "MODERATOR",
          rankColor: "#2ecc71",
          joinDate: "Aug 2021",
          messagesCount: 3890,
          reactionScore: 2410,
          isOnline: false,
        },
        date: "Today at 6:30 AM",
        content: "Verified by staff. High quality contribution and clean methodology. Thread stickied for educational value.",
        likes: 45,
      },
    ],
  },
  {
    tid: "earnings-dropshipping-margin",
    subforumSlug: "earnings-schemes",
    title: "[GUIDE] How to scale high-ticket e-commerce with zero ad spend in 2026",
    prefix: "GUIDE",
    prefixColor: "green",
    author: {
      username: "AlphaMonetize",
      avatarColor: "#8e44ad",
      avatarLetter: "A",
      rank: "MEMBER",
      rankColor: "#9b59b6",
      joinDate: "Nov 2024",
      messagesCount: 88,
      reactionScore: 64,
      isOnline: true,
    },
    date: "Yesterday at 11:20 PM",
    views: 1240,
    replies: 2,
    originalPost: {
      content: "Detailed walkthrough on finding B2B suppliers, negotiating drop-ship arrangements, and driving organic search traffic using programmatic content hubs.",
      signature: "Always be testing.",
    },
    posts: [
      {
        pid: "post-201",
        postNumber: 2,
        author: {
          username: "Vortex99",
          avatarColor: "#e67e22",
          avatarLetter: "V",
          rank: "MEMBER",
          rankColor: "#f39c12",
          joinDate: "Feb 2025",
          messagesCount: 42,
          reactionScore: 19,
          isOnline: false,
        },
        date: "Today at 1:15 AM",
        content: "Thanks for this write-up! Which CRM do you connect to your supplier webhook?",
        likes: 3,
      },
    ],
  },
  {
    tid: "crypto-quiz-rewards-500",
    subforumSlug: "cryptocurrency",
    title: "500$ usdt Code Free Crypto Quiz Bonus Rewards",
    prefix: "AIRDROP",
    prefixColor: "blue",
    author: {
      username: "Blackface54",
      avatarColor: "#2980b9",
      avatarLetter: "B",
      rank: "MEMBER",
      rankColor: "#3498db",
      joinDate: "Apr 2023",
      messagesCount: 319,
      reactionScore: 142,
      isOnline: true,
    },
    date: "Today at 1:40 PM",
    views: 890,
    replies: 1,
    originalPost: {
      content: "Complete the exchange learning quiz to claim voucher code pool. Valid for new and active registered users across all supported regions.",
    },
    posts: [],
  },
  {
    tid: "udemy-1120-courses-pack",
    subforumSlug: "udemy-courses",
    title: "[UDEMY] 1120+ PAID COURSES 100% OFF COUPONS PACK [UPDATED]",
    prefix: "UDEMY",
    prefixColor: "purple",
    isPinned: true,
    author: {
      username: "ddoser",
      avatarColor: "#9c27b0",
      avatarLetter: "D",
      rank: "VIP MEMBER",
      rankColor: "#e91e63",
      joinDate: "May 2021",
      messagesCount: 2410,
      reactionScore: 1820,
      isOnline: true,
    },
    date: "Today at 2:48 AM",
    views: 6520,
    replies: 5,
    originalPost: {
      content: "Massive collection of 100% off 2026 Udemy course coupons covering Python, Next.js, Ethical Hacking & Cybersecurity, Cloud Architecture, AWS Solutions Architect, SEO, and Digital Marketing.",
      signature: "Education should be available to everyone.",
    },
    posts: [
      {
        pid: "post-301",
        postNumber: 2,
        author: {
          username: "student_dev",
          avatarColor: "#16a085",
          avatarLetter: "S",
          rank: "MEMBER",
          rankColor: "#1abc9c",
          joinDate: "Jan 2025",
          messagesCount: 15,
          reactionScore: 8,
          isOnline: true,
        },
        date: "Today at 3:12 AM",
        content: "Thank you so much @ddoser! Got the Python & Next.js full courses for free.",
        likes: 21,
      },
    ],
  },
  {
    tid: "vps-rdp-guide-2026",
    subforumSlug: "vps-rdp",
    title: "GET RDP / VPS FOR FREE 100% WORKING METHOD",
    prefix: "TUTORIAL",
    prefixColor: "gold",
    author: {
      username: "morenoaliaj",
      avatarColor: "#8e44ad",
      avatarLetter: "M",
      rank: "MEMBER",
      rankColor: "#9b59b6",
      joinDate: "Oct 2022",
      messagesCount: 480,
      reactionScore: 290,
      isOnline: true,
    },
    date: "Today at 5:39 AM",
    views: 3100,
    replies: 2,
    originalPost: {
      content: "How to claim free student & startup cloud credits across Oracle Cloud Free Tier, Google Cloud free tier, and GitHub Student Pack for hosting your virtual server environments without paying a dime.",
    },
    posts: [],
  },
  {
    tid: "gaming-supercell-discussion",
    subforumSlug: "general-games",
    title: "\\587X SUPERCELL FA...",
    prefix: "GAMING",
    prefixColor: "red",
    author: {
      username: "snapshot",
      avatarColor: "#8e44ad",
      avatarLetter: "S",
      rank: "MEMBER",
      rankColor: "#9b59b6",
      joinDate: "Feb 2023",
      messagesCount: 210,
      reactionScore: 95,
      isOnline: false,
    },
    date: "Today at 12:48 AM",
    views: 1100,
    replies: 3,
    originalPost: {
      content: "Discussion on top army composition tactics for Town Hall 16 in Clan War Leagues. What is your go-to attack strategy?",
    },
    posts: [],
  },
  {
    tid: "wireguard-private-node-guide",
    subforumSlug: "vpn-and-proxies",
    title: "[GUIDE] Setting up a private WireGuard node with DNS leak protection",
    prefix: "GUIDE",
    prefixColor: "green",
    isPinned: true,
    author: {
      username: "GhostNet",
      avatarColor: "#27ae60",
      avatarLetter: "G",
      rank: "SENIOR MEMBER",
      rankColor: "#2ecc71",
      joinDate: "Mar 2022",
      messagesCount: 840,
      reactionScore: 560,
      isOnline: true,
    },
    date: "22 minutes ago",
    views: 2840,
    replies: 3,
    originalPost: {
      content: `In this guide, we cover creating an isolated WireGuard VPN server on a neutral Linux VPS with custom unbound DNS resolvers to prevent IPv4/IPv6 and WebRTC leaks.\n\n### Requirements:\n- Ubuntu 24.04 or Debian 12 minimal VPS instance\n- WireGuard tools (\`apt install wireguard wireguard-tools\`)\n- Unbound caching DNS resolver to query root servers directly\n\n### Key Benefits:\n- Zero logs retained\n- Chained forwarding with iptables NAT rules\n- Unbound encrypted upstream queries\n\nFeel free to ask questions regarding configuration files below!`,
      signature: "Encrypted packets never lie.",
    },
    posts: [
      {
        pid: "post-wn-1",
        postNumber: 2,
        author: {
          username: "PacketSniffer",
          avatarColor: "#2980b9",
          avatarLetter: "P",
          rank: "MEMBER",
          rankColor: "#3498db",
          joinDate: "Jan 2024",
          messagesCount: 142,
          reactionScore: 89,
          isOnline: true,
        },
        date: "15 minutes ago",
        content: "Great write-up @GhostNet! Did you enable MTU clamp MSS on the WireGuard interface to prevent packet fragmentation?",
        likes: 6,
      },
      {
        pid: "post-wn-2",
        postNumber: 3,
        author: {
          username: "GhostNet",
          avatarColor: "#27ae60",
          avatarLetter: "G",
          rank: "SENIOR MEMBER",
          rankColor: "#2ecc71",
          joinDate: "Mar 2022",
          messagesCount: 840,
          reactionScore: 560,
          isOnline: true,
        },
        date: "8 minutes ago",
        quote: {
          author: "PacketSniffer",
          text: "Did you enable MTU clamp MSS on the WireGuard interface?",
        },
        content: "Yes, exactly! \`iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu\` ensures packets never fragment on mobile connections.",
        likes: 14,
      },
    ],
  },
  {
    tid: "opsec-checklist-researchers",
    subforumSlug: "opsec-privacy-guides",
    title: "[VIP METHOD] Complete Operational Security checklist for independent researchers",
    prefix: "VIP METHOD",
    prefixColor: "red",
    isPinned: true,
    author: {
      username: "NullPointer",
      avatarColor: "#c0392b",
      avatarLetter: "N",
      rank: "VIP MEMBER",
      rankColor: "#e74c3c",
      joinDate: "Dec 2021",
      messagesCount: 2910,
      reactionScore: 2150,
      isOnline: true,
    },
    date: "Yesterday at 4:20 PM",
    views: 4920,
    replies: 2,
    originalPost: {
      content: `A comprehensive operational security checklist for researchers handling sensitive infrastructure.\n\n1. **Hardware Isolation**: Separate host machines; avoid shared peripherals.\n2. **Virtualization Compartmentalization**: Use disposable Qubes domains or live Tails sessions with non-persistent storage.\n3. **Network Layering**: VPN + Tor routing cascades with strict firewall drop policies for non-tunneled traffic.\n4. **Disk Encryption**: Full LUKS encryption with detached headers.\n5. **PGP / GPG hygiene**: Offline subkey generation, revocation certificates kept offline.\n\nDiscipline is the foundation of privacy.`,
      signature: "Trust no one, verify everything.",
    },
    posts: [],
  },
  {
    tid: "canvas-fingerprint-evasion",
    subforumSlug: "antidetect-browsers",
    title: "[ANALYSIS] Canvas and audio fingerprint evasion comparison across browsers",
    prefix: "ANALYSIS",
    prefixColor: "blue",
    author: {
      username: "SilentNode",
      avatarColor: "#2980b9",
      avatarLetter: "S",
      rank: "MEMBER",
      rankColor: "#3498db",
      joinDate: "Aug 2023",
      messagesCount: 420,
      reactionScore: 310,
      isOnline: false,
    },
    date: "Today at 8:40 AM",
    views: 1820,
    replies: 1,
    originalPost: {
      content: "Deep dive analyzing how Canvas 2D noise injection compares to real native driver spoofing across Chromium and Gecko browser engines.",
    },
    posts: [],
  },
  {
    tid: "tor-bridges-obfs4-2026",
    subforumSlug: "tor-and-i2p",
    title: "[RESOURCE] Recommended Tor Bridges & Obfs4 configuration for 2026",
    prefix: "RESOURCE",
    prefixColor: "purple",
    author: {
      username: "CipherPunk",
      avatarColor: "#8e44ad",
      avatarLetter: "C",
      rank: "MEMBER",
      rankColor: "#9b59b6",
      joinDate: "Feb 2024",
      messagesCount: 180,
      reactionScore: 115,
      isOnline: true,
    },
    date: "Today at 11:15 AM",
    views: 2150,
    replies: 2,
    originalPost: {
      content: "Updated list of pluggable transports, Snowflake configurations, and meek-azure bridges for circumventing aggressive DPI firewall filtering.",
    },
    posts: [],
  },
];
