
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { CookieConsent } from "@/components/layout/CookieConsent";
import { Inter } from 'next/font/google';
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  metadataBase: new URL('https://mining.baalvion.com'),
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
    shortcut: '/favicon.ico',
  },
  title: {
    default: 'Baalvion Mining Inc. | Global Mining & Commodity Supply Network',
    template: '%s | Baalvion Mining Inc.'
  },
  description: 'The premier secure marketplace for bulk mineral trade and AI-powered compliance by Baalvion Mining Inc. Connect with verified producers and industrial buyers worldwide.',
  keywords: ['Baalvion', 'mineral trading', 'B2B mining', 'iron ore export', 'lithium supply chain', 'mining compliance', 'industrial minerals', 'commodity supply network'],
  authors: [{ name: 'Baalvion Industries Private Limited' }],
  creator: 'Baalvion Mining Inc.',
  publisher: 'Baalvion Industries Private Limited',
  alternates: {
    canonical: '/',
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://mining.baalvion.com',
    siteName: 'Baalvion Mining Inc.',
    title: 'Baalvion Mining Inc. | Global Mining & Commodity Supply Network',
    description: 'Empowering the world\'s mineral trade with security, transparency, and innovation.',
    // Real PNG image generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Baalvion Mining Inc. | Global B2B Mineral Trading',
    description: 'Secure, transparent, and AI-powered mineral trade for global industries.',
    // Real PNG image generated by app/twitter-image.tsx (file convention).
    creator: '@baalvion',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Baalvion Mining Inc.",
    "legalName": "Baalvion Industries Private Limited",
    "url": "https://mining.baalvion.com",
    "logo": "https://mining.baalvion.com/logo.png",
    "image": "https://mining.baalvion.com/opengraph-image",
    "description": "Global Mining & Commodity Supply Network operated by Baalvion Industries Private Limited.",
    "foundingDate": "2025",
    "email": "trade@baalvion.com",
    "identifier": {
      "@type": "PropertyValue",
      "propertyID": "CIN",
      "value": "U43121OD2025PTC048479"
    },
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Altamount Road, Lodha Altamount",
      "addressLocality": "Mumbai",
      "addressRegion": "Maharashtra",
      "postalCode": "400026",
      "addressCountry": "IN"
    },
    "contactPoint": {
      "@type": "ContactPoint",
      "telephone": "+91 89512 84770",
      "email": "trade@baalvion.com",
      "contactType": "customer service",
      "areaServed": "Worldwide",
      "availableLanguage": ["English", "Hindi"]
    },
    "sameAs": [
      "https://www.linkedin.com/company/baalvion",
      "https://twitter.com/baalvion"
    ]
  };

  const localBusinessSchema = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": "https://mining.baalvion.com/#headquarters",
    "name": "Baalvion Mining Inc. — Headquarters",
    "url": "https://mining.baalvion.com",
    "logo": "https://mining.baalvion.com/logo.svg",
    "telephone": "+91 89512 84770",
    "email": "trade@baalvion.com",
    "priceRange": "$$$",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Altamount Road, Lodha Altamount",
      "addressLocality": "Mumbai",
      "addressRegion": "Maharashtra",
      "postalCode": "400026",
      "addressCountry": "IN"
    }
  };

  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <meta name="google-site-verification" content="NAuMkSOIsTlKlp4DUrjI22woZL6FdoxEFwxoJHh5BYY" />
      </head>
      <body className="font-body antialiased bg-background min-h-screen overflow-x-hidden">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
        <GoogleAnalytics />
        {children}
        <CookieConsent />
        <Toaster />
      </body>
    </html>
  );
}
