import type { Metadata, Viewport } from "next";
import { Inter, Newsreader, Noto_Naskh_Arabic } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import UnifiedAnalytics from "@/components/UnifiedAnalytics";
import { GoogleAnalytics } from "@/components/GoogleAnalytics";
import { AppProvider } from "@/lib/store";
import { MaisonPopup } from "@/components/layout/MaisonPopup";
import type { WelcomeOfferContent } from "@/lib/cms";

// Variable axis rather than five static cuts: one file instead of five, and any weight in
// between is reachable (the UI leans on 300-600).
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Display face. Two predecessors did not work: Cormorant Garamond (old-style revival — reads
// literary, renders weak on screen) and Bodoni Moda (Didone — correct for a fashion masthead but
// too ornate and high-contrast here). Newsreader is the quieter option: moderate stroke contrast,
// near-even weight, upright and architectural rather than decorative, and it stays sturdy at
// caption sizes where a hairline serif breaks up. Its italic is strong, which matters because
// every headline in this design is set italic. Variable, with `opsz` so the browser uses the
// display cut large and the text cut small.
const newsreader = Newsreader({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif",
  style: ["normal", "italic"],
  axes: ["opsz"],
});

// The AE market serves lang="ar-AE" dir="rtl", but neither Latin face carries Arabic glyphs, so
// Arabic fell back to whatever the browser happened to pick. Naskh is the correct register for
// running Arabic text.
const naskh = Noto_Naskh_Arabic({
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-arabic",
  weight: ["400", "500", "600", "700"],
});

/**
 * The site's <html> shell, shared by both root layouts.
 *
 * There are two of them. `<html lang>`/`dir` has to be correct in the SSR
 * response (AE leads in Arabic/RTL), and the only place that is knowable
 * without a dynamic API is the URL — the `[country]` segment. A root layout
 * can read `params`; the old single root layout could not, so it read the
 * country from a middleware-set header via `headers()`. That one call made
 * EVERY route in the app dynamic: the build shipped 61 of 63 routes as `f`
 * with no revalidate window, so nothing on this site was ever cached.
 *
 * Splitting the root in two — `[country]` for the storefront, `(entry)` for the
 * handful of country-less routes — lets the storefront read its locale from
 * `params` and be statically rendered, with identical markup either way.
 */
export { inter, newsreader, naskh };

export const sharedViewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const sharedMetadata: Metadata = {
  metadataBase: new URL("https://www.amarisemaisonavenue.com/"),
  alternates: { canonical: "/" },
  icons: { icon: "/favicon.svg", shortcut: "/favicon.svg", apple: "/favicon.svg" },
  title: {
    default: "AMARISÉ MAISON AVENUE | The Pinnacle of Global Luxury",
    template: "%s | AMARISÉ MAISON AVENUE",
  },
  description:
    "Authenticated pre-owned Hermès, Chanel, Goyard and fine jewelry. Every piece verified in-house before it is listed.",
  keywords: [
    "luxury fashion",
    "bespoke jewelry",
    "high-end watches",
    "heritage couture",
    "private acquisition",
  ],
  authors: [{ name: "Amarisé Maison Avenue" }],
  creator: "Amarisé Maison Avenue",
  publisher: "Amarisé Maison Avenue",
  openGraph: {
    title: "AMARISÉ MAISON AVENUE | The Pinnacle of Global Luxury",
    description: "Authenticated pre-owned Hermès, Chanel, Goyard and fine jewelry.",
    url: "https://www.amarisemaisonavenue.com/",
    siteName: "Amarisé Maison Avenue",
    type: "website",
    // OG image is generated by src/app/opengraph-image.tsx (Next metadata file
    // convention) — replaces the former picsum.photos placeholder.
  },
  twitter: {
    card: "summary_large_image",
    title: "AMARISÉ MAISON AVENUE | Global Luxury",
    description: "The Absolute Standard of Heritage Curation.",
    // Twitter image is generated by src/app/twitter-image.tsx (convention).
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export function RootHtml({
  lang,
  dir,
  welcomeOffer,
  children,
}: {
  lang: string;
  dir: "ltr" | "rtl";
  welcomeOffer: WelcomeOfferContent | null;
  children: React.ReactNode;
}) {
  return (
    <html
      lang={lang}
      dir={dir}
      className={`${inter.variable} ${newsreader.variable} ${naskh.variable} light scroll-smooth`}
    >
      <head>
        <GoogleAnalytics />
        <link rel="preconnect" href="https://picsum.photos" />
        <link rel="preconnect" href="https://madisonavenuecouture.com" />
        {/* Organization + WebSite knowledge-graph entities (server-rendered, static). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "@id": "https://www.amarisemaisonavenue.com/#organization",
              name: "Amarisé Maison Avenue",
              alternateName: "AMARISÉ MAISON AVENUE",
              brand: "Amarisé Maison Avenue",
              url: "https://www.amarisemaisonavenue.com/",
              logo: "https://www.amarisemaisonavenue.com/favicon.svg",
              foundingDate: "2025-03-11",
              description:
                "Luxury resale house specialising in authenticated pre-owned Herm\u00e8s, Chanel, Goyard and fine jewelry. Established 2025.",
              // What the business does and where — the two facts a search/AI engine needs
              // to correctly place this entity (luxury RESALE, not a first-hand fashion house).
              knowsAbout: [
                "Authenticated pre-owned Hermès handbags",
                "Authenticated pre-owned Chanel handbags",
                "Fine jewelry",
                "Luxury watches",
                "Handbag and jewelry authentication",
                "Luxury consignment and resale",
              ],
              areaServed: [
                { "@type": "Country", name: "United States" },
                { "@type": "Country", name: "United Kingdom" },
                { "@type": "Country", name: "United Arab Emirates" },
                { "@type": "Country", name: "India" },
                { "@type": "Country", name: "Singapore" },
              ],
              sameAs: [
                "https://www.instagram.com/amarisemaisonavenue",
                "https://www.facebook.com/amarisemaisonavenue",
                "https://www.linkedin.com/company/amarisemaisonavenue",
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "@id": "https://www.amarisemaisonavenue.com/#website",
              name: "Amarisé Maison Avenue",
              url: "https://www.amarisemaisonavenue.com/",
              publisher: {
                "@id": "https://www.amarisemaisonavenue.com/#organization",
              },
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate:
                    "https://www.amarisemaisonavenue.com/us/search?q={search_term_string}",
                },
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
      </head>
      <body className="font-body antialiased bg-background text-foreground overflow-x-hidden selection:bg-gold selection:text-white">
        <AppProvider>{children}</AppProvider>
        <MaisonPopup initialOffer={welcomeOffer} />
        <Toaster />
        <UnifiedAnalytics slug={process.env.NEXT_PUBLIC_CMS_WEBSITE_SLUG || "amarise-maison-avenue"} />
      </body>
    </html>
  );
}
