apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: baalvion
  labels:
    app:  admin-service
    tier: identity
spec:
  selector: { app: admin-service }
  ports:
    - name:       http
      port:       3021
      targetPort: 3021
    - name:       metrics
      port:       9462
      targetPort: 9462
  type: ClusterIP
