{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile: { type: RuntimeDefault }
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ .name }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ALL] }
            seccompProfile: { type: RuntimeDefault }
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          image: "{{ $.Values.image.registry }}/{{ .name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-config
            - secretRef:
                name: {{ $.Release.Name }}-secret
          env:
            - name: PORT
              value: "{{ .port }}"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .port }}
            initialDelaySeconds: 45
            periodSeconds: 15
          resources:
{{ toYaml $.Values.resources | indent 12 }}
{{- end }}
