apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: baalvion
  labels:
    app:  session-service
    tier: identity
spec:
  selector: { app: session-service }
  ports:
    - name:       http
      port:       3022
      targetPort: 3022
    - name:       metrics
      port:       9463
      targetPort: 9463
  type: ClusterIP
