DROP TABLE IF EXISTS tradeops.carrier_fleet_history;

DROP INDEX IF EXISTS tradeops.uq_vessels_slug;
DROP INDEX IF EXISTS tradeops.uq_vessels_qid;
DROP INDEX IF EXISTS tradeops.idx_vessels_carrier_id;
DROP INDEX IF EXISTS tradeops.idx_vessels_year_built;
DROP INDEX IF EXISTS tradeops.idx_vessels_gt;
DROP INDEX IF EXISTS tradeops.idx_vessels_teu;
DROP INDEX IF EXISTS tradeops.idx_vessels_type_status;
ALTER TABLE tradeops.vessels DROP CONSTRAINT IF EXISTS fk_vessels_carrier;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS slug;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS wikidata_qid;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS carrier_id;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS owner_name;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS builder_name;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS home_port;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS call_sign;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS gross_tonnage;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS length_m;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS beam_m;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS draft_m;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS vessel_class;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS status;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS decommissioned_year;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS image_url;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS source_url;
ALTER TABLE tradeops.vessels DROP COLUMN IF EXISTS last_ingested_at;

DROP INDEX IF EXISTS tradeops.uq_carriers_slug;
DROP INDEX IF EXISTS tradeops.uq_carriers_qid;
DROP INDEX IF EXISTS tradeops.idx_carriers_country_code;
DROP INDEX IF EXISTS tradeops.idx_carriers_capacity_rank;
DROP INDEX IF EXISTS tradeops.idx_carriers_vessel_count;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS slug;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS wikidata_qid;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS legal_name;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS description;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS website;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS headquarters;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS country_code;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS founded_year;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS company_type;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS employee_count;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS parent_name;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS alliance;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS data_source;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS source_url;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS last_ingested_at;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS registry_vessel_count;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS registry_teu;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS registry_dwt;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS registry_gt;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS reported_fleet_size;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS reported_teu;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS market_share_pct;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS reported_source;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS reported_source_url;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS reported_as_of;
ALTER TABLE tradeops.carriers DROP COLUMN IF EXISTS capacity_rank;
