-- Revert 069. The http:// -> https:// image-URL repair is deliberately NOT reverted:
-- re-breaking every image to satisfy symmetry would be vandalism, not a rollback.
ALTER TABLE tradeops.carriers
    DROP COLUMN IF EXISTS founders,
    DROP COLUMN IF EXISTS key_people,
    DROP COLUMN IF EXISTS subsidiaries,
    DROP COLUMN IF EXISTS owners,
    DROP COLUMN IF EXISTS products,
    DROP COLUMN IF EXISTS industry,
    DROP COLUMN IF EXISTS legal_form,
    DROP COLUMN IF EXISTS formed_in,
    DROP COLUMN IF EXISTS dissolved_year,
    DROP COLUMN IF EXISTS stock_exchange,
    DROP COLUMN IF EXISTS ticker,
    DROP COLUMN IF EXISTS isin,
    DROP COLUMN IF EXISTS lei,
    DROP COLUMN IF EXISTS revenue,
    DROP COLUMN IF EXISTS net_profit,
    DROP COLUMN IF EXISTS operating_income,
    DROP COLUMN IF EXISTS total_assets,
    DROP COLUMN IF EXISTS total_equity,
    DROP COLUMN IF EXISTS market_cap,
    DROP COLUMN IF EXISTS financials_currency,
    DROP COLUMN IF EXISTS financials_as_of,
    DROP COLUMN IF EXISTS hq_lat,
    DROP COLUMN IF EXISTS hq_lon,
    DROP COLUMN IF EXISTS image_url,
    DROP COLUMN IF EXISTS image_credit,
    DROP COLUMN IF EXISTS logo_credit,
    DROP COLUMN IF EXISTS wikipedia_title,
    DROP COLUMN IF EXISTS wikipedia_url,
    DROP COLUMN IF EXISTS summary,
    DROP COLUMN IF EXISTS summary_fetched_at,
    DROP COLUMN IF EXISTS social;

ALTER TABLE tradeops.vessels
    DROP COLUMN IF EXISTS net_tonnage,
    DROP COLUMN IF EXISTS displacement_t,
    DROP COLUMN IF EXISTS yard_number,
    DROP COLUMN IF EXISTS designed_to_carry,
    DROP COLUMN IF EXISTS launched_year,
    DROP COLUMN IF EXISTS events,
    DROP COLUMN IF EXISTS image_credit,
    DROP COLUMN IF EXISTS images,
    DROP COLUMN IF EXISTS wikipedia_title,
    DROP COLUMN IF EXISTS wikipedia_url,
    DROP COLUMN IF EXISTS summary,
    DROP COLUMN IF EXISTS summary_fetched_at;
