import { ReportLog } from './types';

// Mock in-memory logger
const logs: ReportLog[] = [];

export class ReportLogger {
    log(logData: Omit<ReportLog, 'id' | 'timestamp'>): void {
        const newLog: ReportLog = {
            ...logData,
            id: `log-${Date.now()}`,
            timestamp: new Date(),
        };
        logs.unshift(newLog);
        console.log(`[ReportLogger] Event logged: Report ${newLog.reportId} generated by ${newLog.generatedBy}`);
    }

    getLogs(): ReportLog[] {
        return [...logs];
    }
}
