apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: baalvion
  labels:
    app:  auth-service
    tier: identity
spec:
  selector: { app: auth-service }
  ports:
    - name:       http
      port:       3001
      targetPort: 3001
    - name:       metrics
      port:       9461
      targetPort: 9461
  type: ClusterIP
