agent {
  data_dir = "/run/spire/data"
  log_level = "INFO"
  server_address = "spire-server.security.svc"
  server_port = "8081"
  trust_domain = "baalvion.gov"
  trust_bundle_path = "/run/spire/bundle/bundle.crt"
}

plugins {
  NodeAttestor "k8s_psat" {
    plugin_data {
      cluster = "apac-production"
    }
  }
  KeyManager "memory" {
    plugin_data {
    }
  }
  WorkloadAttestor "k8s" {
    plugin_data {
      kubelet_read_only_port = 10255
    }
  }
}