-- Fail-closed tenant isolation on the two tables added by 001 and 002.
--
-- Both carry org_id and were shipped without it, which the tenant-isolation audit
-- caught: a missing policy on a tenant table is not a style problem, it is one query
-- away from a candidate's messages being readable by another organisation.
--
-- Generated by enableRlsSql() in @baalvion/tenancy so the policy text is identical to
-- every other service's — including the CR-8 hardening that denies the bypass to the
-- runtime app role itself.

ALTER TABLE "jobs"."application_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs"."application_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "jobs"."application_messages";
CREATE POLICY "tenant_isolation" ON "jobs"."application_messages"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));

ALTER TABLE "jobs"."project_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs"."project_applications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "jobs"."project_applications";
CREATE POLICY "tenant_isolation" ON "jobs"."project_applications"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));
