version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - CASE_SERVICE_URL=http://case-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:8080
      - JWT_SECRET=secret_authority_key

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"

  case-service:
    build: ./services/case-service
    ports:
      - "3002:3002"

  payment-service:
    build: ./services/payment-service
    ports:
      - "8080:8080"
