'use strict';
/**
 * Bulk-creates the 30 Imperialpedia author/contributor profiles supplied in
 * "Imperialpedia All Autors + all Contributers + All Writers + fact Checker"
 * (source doc) into the central CMS so each byline is editable + publishable
 * from admin.baalvion.com → Website → imperialpedia → Authors.
 *
 * Idempotent: pre-fetches existing slugs and skips any that already exist
 * (also treats a 409 from POST as a skip), so re-running is safe.
 *
 * No author photos are set (avatarUrl omitted) — the source doc says
 * "Upload a verified professional photo" for every entry but supplies no
 * actual image, and photos must never be invented or auto-matched. Upload
 * real photos through the admin UI per-author once available.
 *
 * Fields the source doc explicitly marks "leave blank unless verified"
 * (some certifications, LinkedIn/X/video URLs) are omitted rather than
 * guessed.
 *
 * USAGE
 *   # Preview the exact payloads with no network calls:
 *   node scripts/seedImperialpediaAuthors.cjs --dry-run
 *
 *   # Local dev CMS (login flow):
 *   AUTH_URL=http://localhost:3001/v1/auth CMS_URL=http://localhost:3011/api/v1 \
 *   SUPERADMIN_EMAIL=superadmin@baalvion.com SUPERADMIN_PASSWORD=*** \
 *   node scripts/seedImperialpediaAuthors.cjs
 *
 *   # Production (bearer token, e.g. copied from a DevTools /cms/ request
 *   # while logged into admin.baalvion.com as super_admin):
 *   CMS_TOKEN=<bearer> node scripts/seedImperialpediaAuthors.cjs
 */

const AUTH = process.env.AUTH_URL || 'http://localhost:3001/v1/auth';
const CMS = process.env.CMS_URL || 'http://localhost:3011/api/v1';
const TARGET_CMS_BASE = process.env.TARGET_CMS_BASE || null; // e.g. https://admin.baalvion.com/api-bff/knowledge/cms/api/v1
const EMAIL = process.env.SUPERADMIN_EMAIL || 'superadmin@baalvion.com';
const PW = process.env.SUPERADMIN_PASSWORD;
const CMS_TOKEN = process.env.CMS_TOKEN || null;
const SITE = process.env.WEBSITE_SLUG || 'imperialpedia';

const ARGS = process.argv.slice(2);
const DRY_RUN = ARGS.includes('--dry-run');

const CMS_BASE = TARGET_CMS_BASE || CMS;
const BASE = `${CMS_BASE.replace(/\/+$/, '')}/cms/websites/${encodeURIComponent(SITE)}`;

// name/slug/title map 1:1 to the source doc's "Name"/"Slug"/"Editorial title"
// columns. `credentials` = the doc's Credentials column (string). `education`
// and `certifications` are the doc's columns split into arrays. `social`
// only includes URLs the doc gave as real (not "leave blank unless verified").
const AUTHORS = [
  { slug: 'stella-osoba', name: 'Stella Osoba', title: 'Senior Editor, Trading and Investing', credentials: 'CMT, Esq.',
    expertise: ['Technical Analysis', 'Trading', 'Investing', 'Behavioral Finance', 'Financial Markets', 'Risk Management'],
    education: ['University of Warwick — Law'],
    certifications: ['Chartered Market Technician (CMT)'],
    social: { linkedin: 'https://www.linkedin.com/in/stellaosoba/' },
    bio: 'Stella Osoba is a Senior Editor, Trading and Investing at imperialpedia, as well as an attorney, financial writer, technical analyst, and independent trader. She has extensive experience covering financial markets, trading, investing, technical analysis, behavioral finance, and risk management.\n\nOsoba began her professional career in law before moving into financial writing, trading, and technical analysis. Her work has appeared in publications including Technical Analysis of Stocks & Commodities and The Journal of Technical Analysis, as well as financial websites such as GOBankingRates and TradersAdvantage.\n\nShe is a Chartered Market Technician (CMT) and has been actively involved with the CMT Association. She has served in leadership roles within Women in Technical Analysis and has contributed to educational initiatives, including the development of materials for the CMT examination. She has also served as a grader for the CMT Level III examination and has taught and mentored traders and financial professionals.\n\nOsoba’s areas of expertise include technical analysis, trading strategies, financial markets, behavioral finance, risk management, market history, and investment analysis. Her background in law and financial markets provides an interdisciplinary perspective on trading, investing, and financial decision-making.',
    seo: { title: 'Stella Osoba | Senior Editor, Trading and Investing | Imperialpedia', description: 'Stella Osoba is a Senior Editor, Trading and Investing at imperialpedia, attorney, Chartered Market Technician, financial writer, technical analyst, and independent trader.', keywords: ['Stella Osoba', 'Stella Osoba CMT', 'Stella Osoba imperialpedia', 'technical analysis', 'trading', 'investing', 'behavioral finance', 'financial markets', 'risk management', 'Chartered Market Technician', 'CMT', 'financial writer', 'independent trader'] } },

  { slug: 'nathan-reiff', name: 'Nathan Reiff', title: 'Resident Conductor, Harvard Glee Club', credentials: 'D.M.A., M.M., B.A.',
    expertise: ['Investing', 'Trading', 'ETFs', 'Cryptocurrency', 'Alternative Investments', 'Personal Finance'],
    education: ['Yale University — B.A. in Music', 'D.M.A. in Choral Conducting', 'University of Michigan — M.M. in Choral Conducting'],
    certifications: [],
    social: {},
    bio: 'Nathan Reiff is a conductor, educator, vocalist, and financial writer whose professional work spans music, education, and financial publishing. He has written about investing, trading, exchange-traded funds (ETFs), cryptocurrency, and alternative investments.\n\nReiff has an extensive background in choral conducting and music education. He has worked with ensembles including the Yale Glee Club, Yale Camerata, Young People’s Chorus of New York City, and Ann Arbor Cantata Singers. He served as Resident Conductor of the Harvard Glee Club and as a faculty member at Boston Conservatory at Berklee, where he taught choral studies and conducted student ensembles.\n\nHe holds a Bachelor of Arts in Music from Yale University, a Master of Music in Choral Conducting from the University of Michigan, and a Doctor of Musical Arts in Choral Conducting from Yale University.\n\nIn addition to his work as a conductor and educator, Reiff has contributed financial writing on topics including investing, trading, ETFs, cryptocurrency, and alternative investments. His interdisciplinary career combines expertise in music, education, communication, and financial topics.',
    seo: { title: 'Nathan Reiff | Investing, Trading & ETFs Writer | Imperialpedia', description: 'Nathan Reiff is a conductor, educator and financial writer with expertise in investing, trading, ETFs, cryptocurrency and alternative investments.', keywords: ['Nathan Reiff', 'Nathan Reiff imperialpedia', 'investing', 'trading', 'ETFs', 'cryptocurrency', 'alternative investments', 'personal finance', 'financial writer', 'Harvard Glee Club', 'conductor', 'Yale University', 'University of Michigan'] } },

  { slug: 'chip-stapleton', name: 'Chip Stapleton', title: 'Financial Analyst', credentials: 'Series 7, Series 66, Indiana Life, Accident & Health Insurance License',
    expertise: ['Corporate Finance', 'Financial Planning', 'Wealth Management', 'Investing', 'Investment Analysis', 'Technical Analysis', 'Portfolio Construction', 'Business Exit Planning'],
    education: ['Indiana University Jacobs School of Music — B.S./Bachelor’s in Saxophone and Physics', 'Indiana University–Purdue University Indianapolis — M.M. in Music Technology'],
    certifications: ['Series 7', 'Series 66', 'Indiana Life, Accident & Health Insurance License'],
    social: { linkedin: 'https://www.linkedin.com/in/chipstapleton/' },
    bio: 'Chip Stapleton is a financial analyst and member of Imperialpedia Financial Review Board with professional experience in financial planning, wealth management, corporate finance, investment analysis, and business exit planning.\n\nStapleton spent approximately eight years working in finance, with much of his career focused on financial planning and wealth management. As a financial advisor, he worked with individuals and businesses to develop strategies for achieving financial goals. His experience includes case design, investment analysis, investment recommendations, portfolio construction, asset management, financial statement analysis, business planning, and business exit strategies.\n\nStapleton later transitioned into financial analysis, where his work involves analyzing, modeling, and projecting personal and business financial statements. His focus includes helping companies maximize transferable value and assisting business owners with planning for successful exits.\n\nHe holds Series 7 and Series 66 securities licenses and an Indiana Life, Accident, and Health Insurance License. He has also pursued the Chartered Financial Analyst (CFA) program.\n\nStapleton’s academic background combines music, physics, and technology. He earned a bachelor’s degree in Saxophone and Physics from Indiana University’s Jacobs School of Music and a master’s degree in Music Technology from Indiana University–Purdue University Indianapolis.\n\nHis interdisciplinary background in mathematics, analytical thinking, finance, and business strategy informs his approach to financial analysis and investment-related topics.',
    seo: { title: 'Chip Stapleton | Financial Analyst | Corporate Finance & Investing | Imperialpedia', description: 'Chip Stapleton is a financial analyst with experience in corporate finance, financial planning, wealth management, investing, portfolio construction, and business exit strategies.', keywords: ['Chip Stapleton', 'Chip Stapleton imperialpedia', 'financial analyst', 'corporate finance', 'financial planning', 'wealth management', 'investing', 'investment analysis', 'portfolio construction', 'technical analysis', 'business exit strategies', 'financial statements', 'Series 7', 'Series 66'] } },

  { slug: 'dara-abasi-ita', name: 'Dara-Abasi Ita', title: 'Financial Writer', credentials: '',
    expertise: ['Investing', 'Trading', 'Global Markets', 'Financial Markets', 'Private Equity', 'Asset Management', 'DeFi', 'Blockchain', 'Risk Management'],
    education: ['University of Uyo — Bachelor of Laws (LL.B.)'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/daraita/' },
    bio: 'Dara-Abasi Ita is a financial writer and editor whose work focuses on investing, trading, global markets, and financial technology.\n\nIta began his writing career as a member of the editorial board of a student newsletter at the University of Uyo, where he researched and wrote about financial topics including mergers and acquisitions. He later became an editor for Lawverse magazine, a publication focused on legal careers and education.\n\nIn 2020, Ita launched a personal blog covering topics including private equity, asset management, international payments, and risk management. In 2022, he joined blockchain services platform SweetBlocks as a technical writer and decentralized finance analyst, expanding his work into blockchain and financial technology.\n\nHe subsequently wrote for Investing.com, covering global markets, trading, and investing, and has contributed more than 20 articles to the publication. He is also a writer for imperialpedia, where his work covers financial markets and investment-related topics.\n\nIta studied law at the University of Uyo, combining his legal education with professional interests in finance, investing, trading, and emerging financial technologies.',
    seo: { title: 'Dara-Abasi Ita | Financial Writer | Investing & Global Markets | Imperialpedia', description: 'Dara-Abasi Ita is a financial writer covering investing, trading, global markets, private equity, asset management, DeFi, blockchain, and financial technology.', keywords: ['Dara-Abasi Ita', 'Dara-Abasi Ita imperialpedia', 'investing', 'trading', 'global markets', 'financial markets', 'financial writer', 'private equity', 'asset management', 'decentralized finance', 'DeFi', 'blockchain', 'risk management'] } },

  { slug: 'robert-kelly', name: 'Robert Kelly', title: 'Managing Director', credentials: 'Ph.D., MPA',
    expertise: ['Economics', 'Energy Markets', 'General Business', 'Investing', 'Corporate Finance', 'Renewable Energy', 'Natural Gas', 'Energy Infrastructure'],
    education: ['U.S. Military Academy (West Point) — Bachelor’s in Nuclear Engineering', 'Harvard Kennedy School — MPA', 'Harvard University — Ph.D. in Economics'],
    certifications: [],
    social: {},
    videoUrl: 'https://www.xtsenergy.com/',
    bio: 'Robert Kelly is Managing Director of XTS Energy LLC and an experienced energy industry executive with more than three decades of experience in corporate leadership, energy development, investment, and capital formation.\n\nThroughout his career, Kelly has been involved in the development of renewable energy and natural gas projects. He was a founding member of DKRW Energy LLC, where he co-led the development of more than 900 megawatts of wind energy. Earlier in his career, while serving as a senior executive at a major energy company, he founded a wind energy company that later became GE Wind Energy. He also helped establish a solar energy company through a joint venture with Amoco that became part of BP Solar.\n\nKelly has extensive experience in energy investment and project development. He has served as commercial lead or co-lead in raising more than $4.5 billion in capital from private equity investors, strategic investors, and commercial banks for energy projects.\n\nHe has also held senior leadership positions in the energy sector, including serving as chair of Mexico Pacific Limited, LLC, which is developing a large-scale liquefied natural gas project on Mexico’s Pacific Coast.\n\nKelly holds a bachelor’s degree in nuclear engineering from the U.S. Military Academy at West Point, a Master of Public Administration from Harvard Kennedy School, and a Ph.D. in Economics from Harvard University. He also serves as an Executive Professor at the Mays Business School at Texas A&M University and is a member of imperialpedia’s Financial Review Board.',
    seo: { title: 'Robert Kelly | Managing Director | Economics, Energy & Investing | Imperialpedia', description: 'Robert Kelly is Managing Director of XTS Energy and an experienced energy executive specializing in economics, investing, energy markets, renewable energy, natural gas, and capital formation.', keywords: ['Robert Kelly', 'Robert Kelly XTS Energy', 'Robert Kelly imperialpedia', 'XTS Energy', 'energy executive', 'economics', 'investing', 'energy markets', 'renewable energy', 'wind energy', 'solar energy', 'natural gas', 'LNG', 'corporate finance', 'capital formation', 'energy infrastructure'] } },

  { slug: 'michael-rosenston', name: 'Michael Rosenston', title: 'Fact Checker', credentials: '',
    expertise: ['Finance', 'Business', 'Insurance', 'Statistical Analysis', 'Financial Research', 'Data Analysis', 'Risk Analysis'],
    education: ['University of Illinois Urbana–Champaign — B.S. in Statistics', 'Minor in Computer Science'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/michaelrosenston/' },
    bio: 'Michael Rosenston is a fact checker and researcher with experience across finance, business, insurance, statistical analysis, and strategy. He has worked as a fact checker and researcher for imperialpedia since 2020, helping evaluate the accuracy and reliability of financial and business content.\n\nBefore focusing on fact-checking and research, Rosenston worked in the advertising industry, where he applied mathematical models, statistical analysis, and strategic expertise to help clients improve sales and business performance.\n\nHis background also includes internships with Fortune 500 insurance companies, providing him with experience and insight into the insurance industry and financial services.\n\nRosenston holds a Bachelor of Science in Statistics from the University of Illinois at Urbana–Champaign, where he also completed a minor in Computer Science. His combination of statistical and analytical training supports his work researching and evaluating financial, business, and insurance information.',
    seo: { title: 'Michael Rosenston | Finance & Insurance Fact Checker | Imperialpedia', description: 'Michael Rosenston is a fact checker and researcher specializing in finance, business, insurance, statistics, and financial research.', keywords: ['Michael Rosenston', 'Michael Rosenston imperialpedia', 'fact checker', 'finance fact checker', 'financial researcher', 'insurance', 'business', 'statistics', 'data analysis', 'financial research', 'insurance research', 'imperialpedia fact checker'] } },

  { slug: 'jb-maverick', name: 'J.B. Maverick', title: 'Writer and Editor', credentials: '',
    expertise: ['Trading', 'Forex', 'Commodities', 'Stock Markets', 'Futures', 'Investing', 'Finance', 'Business'],
    education: ['Bachelor of Science in Psychology'],
    certifications: [],
    social: {},
    videoUrl: 'https://x.com/bogartmaverick',
    bio: 'J.B. Maverick is a financial writer, editor, active trader, and former commodity futures broker and stock market analyst with more than 17 years of experience in financial markets.\n\nMaverick began writing about financial markets and forex trading in 2007 and has since written extensively about trading, finance, and business. His work covers stock markets, futures, foreign exchange, commodities, and broader financial and business topics. He has published hundreds of articles and has also written a book on futures trading.\n\nIn addition to his work in financial publishing, Maverick is an author and screenwriter. He wrote the psychological thriller A Cross of Hearts and has developed a film script about the life of legendary trader Jesse Livermore. His broader writing interests also include political, social, and religious commentary.\n\nMaverick holds a Bachelor of Science in Psychology. His combination of professional market experience and financial writing expertise informs his work on trading, investing, and financial markets.',
    seo: { title: 'J.B. Maverick | Trader, Financial Writer & Editor | Imperialpedia', description: 'J.B. Maverick is an experienced trader, former commodity futures broker, stock market analyst, financial writer, and editor specializing in forex, futures, stocks, finance, and business.', keywords: ['J.B. Maverick', 'JB Maverick', 'J.B. Maverick imperialpedia', 'forex trading', 'futures trading', 'commodity trading', 'stock market', 'stock market analyst', 'financial writer', 'finance writer', 'investing', 'trading', 'commodities', 'business'] } },

  { slug: 'julius-mansa', name: 'Julius Mansa', title: 'Chief Finance & Operations Officer, STEM from Dance', credentials: 'Master of Finance',
    expertise: ['Corporate Finance', 'FinTech', 'Investing', 'Personal Finance', 'Real Estate', 'Asset Management', 'Corporate Governance', 'Supply Chain Finance'],
    education: ['Colorado State University — Master of Finance, specialization in Information Technology', 'Indiana University — Bachelor of Interdisciplinary Studies'],
    certifications: [],
    social: {},
    bio: 'Julius Mansa is a finance and operations professional, educator, researcher, and member of imperialpedia’s Financial Review Board. He has more than 15 years of experience in financial management, corporate finance, accounting, operations, logistics, real estate, and nonprofit management.\n\nMansa’s professional experience includes senior financial analyst and financial controller roles, as well as leadership positions overseeing finance functions for nonprofit organizations. His work in logistics has included supply chain finance management for regional and international third-party logistics companies. He also spent more than three years serving as a fractional chief financial officer for an Indianapolis-based real estate development firm with a multimillion-dollar portfolio.\n\nIn 2020, Mansa founded MaxPoint Advisors, a CFO advisory firm serving medium-sized businesses in fast-growing industries. His consulting work focuses on financial management, strategic planning, and business growth.\n\nMansa is also an educator and researcher whose teaching areas have included intermediate accounting, managerial finance, risk management, corporate valuation, portfolio management, and financial economics. In 2020, he received a U.S. Department of State Fulbright Program research award for work related to financial technology.\n\nHis academic research interests include FinTech, asset management, capital structures, Islamic banking and economics, supply chain finance, microfinance, corporate governance, and investor behavior.\n\nMansa holds a Master of Finance with a specialization in Information Technology from Colorado State University and a Bachelor of Interdisciplinary Studies from Indiana University.',
    seo: { title: 'Julius Mansa | Finance, FinTech & Investing Expert | Imperialpedia', description: 'Julius Mansa is a finance and operations professional, educator, researcher, and Financial Review Board member specializing in corporate finance, FinTech, investing, real estate, and asset management.', keywords: ['Julius Mansa', 'Julius Mansa imperialpedia', 'corporate finance', 'FinTech', 'investing', 'personal finance', 'real estate', 'financial management', 'asset management', 'corporate governance', 'supply chain finance', 'CFO', 'financial technology', 'investor behavior', 'MaxPoint Advisors'] } },

  { slug: 'alex-lielacher', name: 'Alex Lielacher', title: 'Founder & Managing Director, Rise Up Media', credentials: '',
    expertise: ['Bitcoin', 'Blockchain', 'Cryptocurrency', 'Digital Assets', 'Capital Markets', 'Fixed Income', 'Crypto Finance', 'Content Marketing'],
    education: ['Bayes Business School, City University London — BSc in Investment & Financial Risk Management'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/alexanderlielacher/', x: 'https://x.com/AlexLielacher' },
    bio: 'Alex Lielacher is a financial writer, content marketer, and former banker specializing in Bitcoin, blockchain, cryptocurrency, digital assets, and capital markets. He is the Founder and Managing Director of Rise Up Media, a Bitcoin-focused content marketing agency that works with cryptocurrency and blockchain companies.\n\nAlex began his career in London on the European High Yield Trading Desk at the Royal Bank of Scotland, where he traded sub-investment-grade corporate bonds and credit default swaps. He later joined Australia & New Zealand Bank’s London office as a Fixed Income Salesperson, working with private banks, commercial banks, and mutual funds in German-speaking markets.\n\nAfter more than five years in banking and capital markets, Alex transitioned into financial writing and content marketing. He has contributed to blockchain and cryptocurrency publications covering topics including real estate tokenization, token-based crowdfunding, digital asset trading strategies, Bitcoin, and broader developments in crypto finance.\n\nThrough Rise Up Media, Alex works with Bitcoin and cryptocurrency startups to develop educational and engaging content designed to communicate complex financial and technological concepts to broader audiences.\n\nAlex has written for imperialpedia since December 2021. He holds a Bachelor of Science in Investment & Financial Risk Management from Bayes Business School, City University London.',
    seo: { title: 'Alex Lielacher | Bitcoin, Blockchain & Cryptocurrency Writer | Imperialpedia', description: 'Alex Lielacher is a former bond trader and financial writer specializing in Bitcoin, blockchain, cryptocurrency, digital assets, capital markets, and crypto finance.', keywords: ['Alex Lielacher imperialpedia', 'Bitcoin writer', 'blockchain writer', 'cryptocurrency writer', 'Bitcoin', 'blockchain', 'cryptocurrency', 'digital assets', 'crypto finance', 'capital markets', 'fixed income', 'bond trading', 'cryptocurrency investing', 'Rise Up Media'] } },

  { slug: 'vikki-velasquez', name: 'Vikki Velasquez', title: 'Fact Checker', credentials: '',
    expertise: ['Research', 'Fact-Checking', 'Writing', 'Editing', 'Public Policy', 'Financial Research', 'Educational Content'],
    education: ['Virginia Commonwealth University — B.A. with Honors in Gender, Sexuality, and Women’s Studies', 'Minor in Religious Studies'],
    certifications: ['Volunteer Management Certification — The Community Foundation for a Greater Richmond'],
    social: { linkedin: 'https://www.linkedin.com/in/vikkivelasquez/' },
    bio: 'Vikki Velasquez is a fact-checker and researcher with experience in research, writing, editing, educational programming, and nonprofit leadership. She joined imperialpedia as a fact-checker in 2021.\n\nBefore joining imperialpedia, Velasquez served as Program Manager and Volunteer Coordinator at Leadership Metro Richmond, a nonprofit organization focused on developing servant leadership. In that role, she researched social and economic issues affecting the Greater Richmond community, including housing, education, wealth inequality, and historical legacy.\n\nHer work also included researching and preparing content for presentations, publications, and educational programs; revising and editing educational materials; and developing instructional resources for program participants, board members, and facilitators. She also trained and coached volunteer instructors who delivered youth leadership programs.\n\nVelasquez’s background in research and education provides an interdisciplinary perspective on social and economic issues and the ways they can influence individual and community outcomes.\n\nShe earned a Bachelor of Arts with honors in Gender, Sexuality, and Women’s Studies, with a minor in Religious Studies, from Virginia Commonwealth University. She also holds a volunteer management certification from The Community Foundation for a Greater Richmond.',
    seo: { title: 'Vikki Velasquez | Fact Checker & Researcher | Imperialpedia', description: 'Vikki Velasquez is an imperialpedia fact-checker with expertise in research, writing, editing, public policy, educational content, and nonprofit leadership.', keywords: ['Vikki Velasquez', 'Vikki Velasquez imperialpedia', 'fact checker', 'researcher', 'financial fact checking', 'research', 'writing', 'editing', 'public policy', 'educational content', 'nonprofit leadership', 'Virginia Commonwealth University'] } },

  { slug: 'erika-rasure', name: 'Erika Rasure', title: 'Founder, Crypto Goddess', credentials: 'PhD, MS',
    expertise: ['Cryptocurrency', 'FinTech', 'Personal Finance', 'Financial Therapy', 'Economics', 'Investing', 'Digital Assets', 'Blockchain', 'Insurance'],
    education: ['Stephens College — B.A. in Law, Philosophy, and Rhetoric, minor in Political Science', 'University of Missouri — M.S. in Consumer Economics', 'Kansas State University — Ph.D. in Personal Financial Planning'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/erikarasure/' },
    bio: 'Dr. Erika Rasure is a financial therapist, educator, cryptocurrency and personal finance expert, and founder of Crypto Goddess. She is a member of imperialpedia’s Financial Review Board and has more than a decade of experience in financial education and financial therapy.\n\nRasure founded Crypto Goddess in 2022 as an educational platform and community designed to help women develop the knowledge and confidence to participate in cryptocurrency, blockchain, digital assets, and the evolving financial system.\n\nHer work combines personal finance education with an understanding of the human and behavioral dimensions of financial decision-making. She has focused on helping individuals connect technical financial planning with their personal goals, values, and financial behaviors.\n\nA longtime advocate of financial technology, Rasure incorporated FinTech topics into personal finance education, including cryptocurrency and blockchain. She also helped develop a FinTech curriculum track within the Management and Information Systems degree program at Maryville University.\n\nAs a university educator, Rasure has taught subjects related to personal finance, financial planning, and financial technology. Her work focuses on preparing individuals to understand emerging financial technologies and make informed decisions about their financial futures.\n\nRasure earned a Bachelor of Arts in Law, Philosophy, and Rhetoric, with a minor in Political Science, from Stephens College. She earned a Master of Science in Consumer Economics from the University of Missouri and a Ph.D. in Personal Financial Planning from Kansas State University.',
    seo: { title: 'Dr. Erika Rasure | Cryptocurrency, FinTech & Personal Finance Expert | Imperialpedia', description: 'Dr. Erika Rasure is a financial therapist, educator, cryptocurrency and personal finance expert, and founder of Crypto Goddess specializing in FinTech, digital assets, blockchain, and financial education.', keywords: ['Erika Rasure', 'Dr. Erika Rasure', 'Erika Rasure imperialpedia', 'Crypto Goddess', 'cryptocurrency', 'FinTech', 'personal finance', 'financial therapy', 'blockchain', 'digital assets', 'investing', 'economics', 'financial education', 'financial planning'] } },

  { slug: 'allie-grace-garnett', name: 'Allie Grace Garnett', title: 'Financial Writer and Editor', credentials: 'MBA',
    expertise: ['Cryptocurrency', 'Personal Finance', 'Digital Assets', 'Climate Finance', 'Sustainable Investing', 'ESG', 'Renewable Energy', 'Financial Markets'],
    education: ['Harvard Business School — Master of Business Administration (MBA)', 'Northeastern University — B.S. in Civil and Environmental Engineering'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/alliegrace/' },
    bio: 'Allie Grace Garnett is a financial writer and editor with more than five years of experience covering cryptocurrency, digital assets, personal finance, climate finance, and sustainable investing. She began her career in traditional finance before transitioning into financial journalism and editorial work.\n\nAs a journalist, Allie reported on cryptocurrency and led coverage of global environmental, social, and governance (ESG) developments for MT Newswires, a financial news service with global distribution. She also contributed to early efforts to develop a digital assets content strategy at The Motley Fool. Her cryptocurrency writing has appeared in publications including Decrypt and other financial and technology outlets.\n\nBefore entering journalism, Allie worked in traditional finance with a focus on climate-related and sustainable investments. She co-founded an energy-efficiency project finance firm and worked on raising capital for institutional-scale renewable energy funds.\n\nHer interest in writing and editing began during high school, when she served as an editor for her school’s award-winning newspaper. Her combined background in finance, engineering, journalism, and sustainable investment gives her a multidisciplinary perspective on emerging financial technologies and climate-related financial issues.\n\nAllie holds a Master of Business Administration from Harvard Business School and a Bachelor of Science in Civil and Environmental Engineering from Northeastern University.',
    seo: { title: 'Allie Grace Garnett | Cryptocurrency, Personal Finance & Climate Finance Writer | Imperialpedia', description: 'Allie Grace Garnett is a financial writer and editor specializing in cryptocurrency, digital assets, personal finance, climate finance, ESG, and sustainable investing.', keywords: ['Allie Grace Garnett imperialpedia', 'cryptocurrency writer', 'crypto writer', 'digital assets', 'personal finance', 'climate finance', 'sustainable investing', 'ESG', 'renewable energy', 'cryptocurrency', 'financial writer', 'financial editor', 'Harvard Business School', 'Northeastern University'] } },

  { slug: 'cierra-murry', name: 'Cierra Murry', title: 'Founder & CEO, Murry Consulting', credentials: 'B.S. in Commerce, Finance & Accounting',
    expertise: ['Banking', 'Investing', 'Loans', 'Mortgages', 'Real Estate', 'Credit Risk', 'Financial Analysis', 'Banking Compliance', 'Loan Review', 'Underwriting'],
    education: ['DePaul University — Bachelor of Science in Commerce, Finance, and Accounting'],
    certifications: ['Notary Loan Signing Agent', 'FINRA Non-Public Arbitrator'],
    social: {},
    bio: 'Cierra Murry is a financial services professional, banking compliance and credit risk specialist, and member of imperialpedia’s Financial Review Board. She has more than 15 years of experience in financial analysis, underwriting, loan documentation, loan review, banking compliance, and credit risk management.\n\nThroughout her career, Murry has held positions across specialty insurance, public accounting audit, financial planning and analysis, mutual fund investment services, and banking. During much of her career at a large private bank, she analyzed financial statements and tax returns, assessed credit risk for consumer, commercial, and commercial real estate loans, and evaluated compliance with banking laws and regulations.\n\nMurry is the Founder and CEO of Murry Consulting, where she provides banking compliance, credit risk management, and loan review services to financial institutions. Her experience includes reviewing securities-based lending, premium financing, asset-based lending, cash-flow lending, small-business, middle-market, corporate, and institutional transactions.\n\nIn addition to her consulting work, Murry provides loan signing services and helps ensure that borrowers properly complete loan documentation. She also serves as a FINRA non-public arbitrator, participating in the resolution of securities-related disputes between investors and brokerage firms.\n\nMurry earned a Bachelor of Science in Commerce, Finance, and Accounting from DePaul University.',
    seo: { title: 'Cierra Murry | Banking, Credit Risk & Lending Expert | Imperialpedia', description: 'Cierra Murry is a banking and credit risk professional with 15+ years of experience in financial analysis, underwriting, loan review, banking compliance, mortgages, and real estate finance.', keywords: ['Cierra Murry', 'Cierra Murry imperialpedia', 'banking', 'credit risk', 'loan underwriting', 'loan review', 'mortgages', 'real estate finance', 'financial analysis', 'banking compliance', 'investing', 'lending', 'Murry Consulting', 'FINRA arbitrator'] } },

  { slug: 'troy-segal', name: 'Troy Segal', title: 'Senior Financial Editor & Writer', credentials: 'B.A., M.A.',
    expertise: ['Personal Finance', 'Wealth Management', 'Investing', 'Business', 'Real Estate', 'Taxes', 'Credit', 'Insurance', 'Retirement', 'Financial Literacy'],
    education: ['Harvard College — B.A. in History & Literature', 'New York University — M.A. in Costume Studies'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/troysegal/', x: 'https://x.com/troysegal?lang=en' },
    bio: 'Troy Segal is an editor and writer with more than 20 years of experience covering personal finance, wealth management, and business from the consumer’s perspective. Her work focuses on helping readers understand complex financial topics, including investing, taxes, real estate, credit, insurance, and money management.\n\nDuring her years at Business Week, Segal co-founded the publication’s "Personal Business" section, which covered financial and consumer-affairs topics from the individual’s point of view. She later served as editor of the Social Issues department, overseeing coverage of education, health care, and workplace issues.\n\nSegal has also worked in financial publishing, including editing for InvestmentNews. Her writing and editorial experience extends to end-of-life legal and financial issues, as well as a broad range of lifestyle and consumer topics.\n\nEarlier in her career, Segal served as senior editor of Zagat Survey and Where New York and as deputy editor of Women’s Wear Daily. She has edited a range of publications and guides, including Zagat Guides, the Opinionated Guide to Dining, and TONY Awards program books.\n\nSegal earned a bachelor’s degree in History and Literature from Harvard College and a master’s degree in Costume Studies from New York University.',
    seo: { title: 'Troy Segal | Personal Finance & Wealth Management Editor | Imperialpedia', description: 'Troy Segal is an editor and writer with 20+ years of experience covering personal finance, wealth management, investing, real estate, taxes, credit, and business.', keywords: ['Troy Segal', 'Troy Segal imperialpedia', 'personal finance', 'wealth management', 'financial writer', 'financial editor', 'investing', 'real estate', 'taxes', 'credit', 'insurance', 'financial literacy', 'business', 'consumer finance', 'money management'] } },

  { slug: 'hans-daniel-jasperson', name: 'Hans Daniel Jasperson', title: 'Fact Checker', credentials: 'MPA, BA',
    expertise: ['Public Policy', 'Government Affairs', 'Workforce Development', 'Economic Justice', 'Nonprofit Management', 'Research', 'Fact-Checking'],
    education: ['University of Utah — MPA', 'B.A. in Spanish Language and Literature'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/dannyjasperson/' },
    bio: 'Hans Daniel Jasperson is a fact-checker and policy researcher with more than a decade of experience providing fact-based information and analysis to business leaders, policymakers, and consumers. He has worked as a fact-checker for imperialpedia since 2019, helping ensure the accuracy, reliability, and quality of published content.\n\nBefore joining imperialpedia, Jasperson served as Director of Public Policy Research at Management & Training Corporation, where he prepared policy briefs and research for the U.S. Congress, federal agencies, and state policymakers. His policy work covered areas including criminal justice, education, workforce development, and career training.\n\nEarlier in his career, Jasperson worked as a program director for Salt Lake Community Action Program, where he developed and managed nonprofit programs serving low-income communities. His work included advocating for policies and resources aimed at addressing economic inequality and improving opportunities for underserved communities.\n\nJasperson’s professional background combines research, public policy, government affairs, nonprofit management, workforce development, and fact-checking. His work emphasizes the importance of accurate and reliable information in supporting sound decision-making in government, business, and personal life.\n\nJasperson earned a Bachelor of Arts in Spanish Language and Literature and a Master of Public Administration from the University of Utah.',
    seo: { title: 'Hans Daniel Jasperson | Fact Checker & Policy Researcher | Imperialpedia', description: 'Hans Daniel Jasperson is a fact checker and policy researcher specializing in public policy, government affairs, workforce development, economic justice, and nonprofit management.', keywords: ['Hans Daniel Jasperson', 'Hans Jasperson', 'imperialpedia fact checker', 'fact checker', 'public policy', 'government affairs', 'workforce development', 'economic justice', 'nonprofit management', 'policy research', 'government policy', 'economic inequality', 'workforce training'] } },

  { slug: 'jonathan-ponciano', name: 'Jonathan Ponciano', title: 'Financial Journalist & Editor', credentials: '',
    expertise: ['Markets', 'Finance', 'Cryptocurrency', 'Investing', 'FinTech', 'Technology', 'Entrepreneurship', 'Financial Journalism'],
    education: ['University of North Carolina at Chapel Hill — Dual Degree in Business Journalism and Economics', 'Columbia Business School — MBA candidate'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/jonathan-ponciano/', x: 'https://x.com/jon_ponciano' },
    bio: 'Jonathan Ponciano is a financial journalist and editor with nearly a decade of experience covering finance, markets, technology, entrepreneurship, investing, cryptocurrency, and financial technology.\n\nPonciano has spent several years reporting and editing stories focused on financial markets and business. His journalism has included profiling prominent executives and business leaders, including chairmen and CEOs of companies operating in emerging and technology-driven industries.\n\nHis reporting experience includes coverage of markets, finance, technology, entrepreneurship, investing, cryptocurrency, and fintech. He has also researched and calculated the net worths of some of the world’s wealthiest individuals.\n\nPonciano previously edited articles for imperialpedia in 2017 and 2019 before returning to the publication. His work combines financial reporting with an interest in emerging technologies and the companies shaping modern markets.\n\nPonciano earned a dual degree in Business Journalism and Economics from the University of North Carolina at Chapel Hill. He is currently pursuing an MBA at Columbia Business School.',
    seo: { title: 'Jonathan Ponciano | Finance, Markets & Cryptocurrency Journalist | Imperialpedia', description: 'Jonathan Ponciano is a financial journalist and editor specializing in markets, finance, cryptocurrency, investing, fintech, technology, and entrepreneurship.', keywords: ['Jonathan Ponciano', 'Jonathan Ponciano imperialpedia', 'financial journalist', 'finance writer', 'markets', 'investing', 'cryptocurrency', 'crypto', 'fintech', 'financial markets', 'technology', 'entrepreneurship', 'business journalism'] } },

  { slug: 'gordon-scott', name: 'Gordon Scott', title: 'Financial Education Consultant', credentials: 'CMT',
    expertise: ['Technical Analysis', 'Trading', 'Investing', 'Instructional Design', 'Financial Education', 'Penny Stocks', 'Forex', 'Futures', 'Securities'],
    education: ['Brigham Young University — B.A. in Technical Writing', 'San Jose State University — Master’s Degree in Instructional Technology'],
    certifications: ['Chartered Market Technician (CMT)'],
    social: { linkedin: 'https://www.linkedin.com/in/gordonbscott/', x: 'https://x.com/gordonscottcmt' },
    bio: 'Gordon Scott is a financial education consultant, active investor, trader, and technical analysis specialist with more than 20 years of experience in investing, trading, and financial education. He has traded and provided education covering securities, futures, forex, and penny stocks.\n\nScott has more than 15 years of experience as a trading coach and has held roles in financial education, instructional design, content management, and academic instruction. He teaches imperialpedia Academy’s Penny Stock Trading course and has developed educational programs designed to help individual traders and investors understand financial markets and trading strategies.\n\nFrom 2013 to 2018, Scott served as Managing Director of the Chartered Market Technician (CMT) designation’s examination program for the CMT Association. The CMT designation is a recognized professional credential in technical analysis.\n\nScott previously served as a content manager at Investools, where he developed online curriculum and oversaw educational content related to trading strategies. He also spent 10 years with IBM, developing instructional materials and working on business process refinement, and served as an adjunct instructor in organizational strategy and leadership at Brigham Young University.\n\nScott is the co-author of "Invest to Win" with Toni Turner, a book covering investment approaches and the GainsMaster Investing method.\n\nHe earned a Bachelor of Arts in Technical Writing from Brigham Young University and a master’s degree in Instructional Technology from San Jose State University. He is a Chartered Market Technician (CMT) and a member of the CMT Association.',
    seo: { title: 'Gordon Scott | Technical Analysis & Trading Expert | Imperialpedia', description: 'Gordon Scott is a financial education consultant, trader, and Chartered Market Technician with 20+ years of experience in technical analysis, investing, trading, and financial education.', keywords: ['Gordon Scott', 'Gordon Scott imperialpedia', 'technical analysis', 'trading', 'investing', 'CMT', 'Chartered Market Technician', 'financial education', 'trading coach', 'penny stocks', 'forex trading', 'futures trading', 'instructional design', 'financial markets'] } },

  { slug: 'betsy-petrick', name: 'Betsy Petrick', title: 'Fact Checker', credentials: 'MBA, MA, BA',
    expertise: ['International Business', 'International Finance', 'International Political Economy', 'Public Policy', 'Economics', 'Financial Markets', 'Global Economy', 'Business Journalism'],
    education: ['Brandeis University — M.A.', 'Northeastern University — MBA', 'Ohio Wesleyan University — B.A.'],
    certifications: [],
    social: {},
    bio: 'Betsy Petrick is a fact checker and journalist with a 30-year career covering international economics, international finance, international business, international political economy, and public policy. Her professional background also includes experience in international finance, academia, and professional services.\n\nThroughout her journalism career, Petrick has covered a broad range of business and economic topics, including mortgage lending practices, Federal Reserve policy, financial markets, business strategy, international currencies, and the global economy. Her work has appeared across television news and online publishing.\n\nPetrick brings an interdisciplinary perspective to financial and economic reporting, drawing on professional experience beyond journalism to examine how government policy, business strategy, financial markets, and international economic developments affect different participants in the global economy.\n\nHer academic and professional interests center on understanding how individual countries interact within the international economic and political system. Her background in international finance and academia has further informed her approach to researching and analyzing complex economic and business topics.\n\nPetrick earned an MBA with a focus on international business management from Northeastern University and an M.A. focused on international political economy from Brandeis University. She also earned a B.A. from Ohio Wesleyan University.',
    seo: { title: 'Betsy Petrick | International Finance & Economics Fact Checker | Imperialpedia', description: 'Betsy Petrick is a fact checker and journalist with 30 years of experience covering international finance, economics, business, public policy, and the global economy.', keywords: ['Betsy Petrick', 'Betsy Petrick imperialpedia', 'fact checker', 'international finance', 'international economics', 'international business', 'international political economy', 'public policy', 'global economy', 'financial markets', 'business journalism', 'Federal Reserve', 'international currencies'] } },

  { slug: 'elvis-picardo', name: 'Elvis Picardo', title: 'Portfolio Manager', credentials: 'CFA',
    expertise: ['Portfolio Management', 'Market Analysis', 'Investment Strategy', 'Equity Research', 'Fundamental Analysis', 'Options', 'Investing', 'Capital Markets', 'Advanced Investment Strategies'],
    education: ['Karnatak University — Bachelor of Engineering in Electronics & Communication', 'Bombay University — Master of Management Studies'],
    certifications: ['Chartered Financial Analyst (CFA)', 'Canadian Investment Manager'],
    social: { linkedin: 'https://www.linkedin.com/in/elvispicardo/' },
    bio: 'Elvis Picardo is a portfolio manager and capital markets professional with more than 25 years of experience across investment management, market strategy, and equity research. He has more than 15 years of experience as a strategist and equity analyst and currently works as a portfolio manager at iA Private Wealth.\n\nPicardo’s areas of expertise include market analysis and investment strategy, equity research, fundamental analysis, options, portfolio management, and advanced investment strategies. He has contributed regularly to imperialpedia and has also written for publications including The Money Letter, Investor’s Digest, Reuters.com, and Report on Mining.\n\nHis financial-market commentary and analysis have appeared through major news organizations and media outlets, including Reuters, Report on Business TV, and CBC. His work focuses on helping investors understand markets, evaluate investments, and make informed financial decisions.\n\nPicardo earned a Bachelor of Engineering in Electronics and Communication from Karnatak University in India and a Master of Management Studies from Bombay University. He is a Chartered Financial Analyst (CFA) and a Canadian Investment Manager.',
    seo: { title: 'Elvis Picardo | Portfolio Manager & Investment Strategist | Imperialpedia', description: 'Elvis Picardo is a portfolio manager and CFA with 25+ years of capital markets experience specializing in equity research, market analysis, investment strategy, options, and portfolio management.', keywords: ['Elvis Picardo', 'Elvis Picardo imperialpedia', 'portfolio manager', 'CFA', 'Canadian Investment Manager', 'investment strategist', 'equity research', 'fundamental analysis', 'options trading', 'portfolio management', 'capital markets', 'investing', 'market analysis', 'investment strategy'] } },

  { slug: 'james-chen', name: 'James Chen', title: 'Former Director of Investing & Trading Content', credentials: 'CMT, CFTe, RIA',
    expertise: ['Investing', 'Trading', 'Technical Analysis', 'Financial Markets', 'Foreign Exchange', 'Stocks', 'ETFs', 'Options', 'Commodities', 'Fixed Income', 'Currencies'],
    education: ['Tufts University — Bachelor’s Degree'],
    certifications: ['Chartered Market Technician (CMT)', 'Certified Financial Technician (CFTe)', 'Registered Investment Adviser (RIA)'],
    social: { linkedin: 'https://www.linkedin.com/in/jameschencontent/', x: 'https://x.com/JamesChenFX' },
    bio: 'James Chen, CMT, is a financial markets professional, author, and former director of investing and trading content at imperialpedia. He has two decades of experience in the financial markets as a trader, investor, registered investment adviser, and global market strategist.\n\nChen previously served as head of research at Gain Capital and has extensive expertise across stocks, ETFs, options, commodities, fixed income, currencies, and foreign exchange. His work combines market research and technical analysis with practical experience in trading and investing.\n\nHe is the author of "Essentials of Technical Analysis for Financial Markets" and "Essentials of Foreign Exchange Trading," both published by John Wiley & Sons. He has also contributed to financial education through instructional content, seminars, and conferences.\n\nChen has appeared as a guest expert on financial news outlets including CNBC, Bloomberg TV, and Reuters. He is a Chartered Market Technician (CMT), Certified Financial Technician (CFTe), and Registered Investment Adviser (RIA), and is a former Commodity Trading Advisor (CTA).\n\nChen earned his bachelor’s degree from Tufts University.',
    seo: { title: 'James Chen | Trading & Technical Analysis Expert | Imperialpedia', description: 'James Chen is a financial markets expert, author, and former imperialpedia director with 20 years of experience in trading, investing, technical analysis, and global markets.', keywords: ['James Chen', 'James Chen CMT', 'James Chen imperialpedia', 'trading', 'investing', 'technical analysis', 'financial markets', 'CMT', 'CFTe', 'registered investment adviser', 'forex trading', 'foreign exchange', 'stocks', 'ETFs', 'options', 'commodities', 'market strategist'] } },

  { slug: 'jason-fernando', name: 'Jason Fernando', title: 'Director', credentials: '',
    expertise: ['Value Investing', 'Financial Analysis', 'Investment Analysis', 'Financial Modeling', 'Financial Statements', 'Business Management', 'Stock Market', 'Fundamental Analysis'],
    education: ['University of British Columbia — B.A., History (Honours)'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/jasonfernando' },
    bio: 'Jason Fernando is a professional investor, financial writer, and director with expertise in value investing, financial analysis, financial modeling, and business management.\n\nFernando began investing at age 15 and developed a particular interest in value investing. He founded Vancouver Value Investing to share investment insights and help investors develop a deeper understanding of fundamental investing principles.\n\nHis professional experience includes analyzing financial statements, building financial models, evaluating businesses, and applying fundamental analysis to investment decisions. He actively manages his own stock portfolio using a value-investing approach influenced by investors such as Warren Buffett, Seth Klarman, and Prem Watsa.\n\nFernando is also passionate about financial education and communicating complex business and financial concepts in an accessible way. Through his writing and investment education work, he aims to help investors better understand businesses, markets, and long-term investing principles.\n\nHe earned a Bachelor of Arts in History, with Honours, from the University of British Columbia.',
    seo: { title: 'Jason Fernando | Value Investing & Financial Analysis Expert | Imperialpedia', description: 'Jason Fernando is a professional investor and financial writer specializing in value investing, financial analysis, financial modeling, and fundamental investment research.', keywords: ['Jason Fernando', 'Jason Fernando imperialpedia', 'value investing', 'financial analysis', 'investment analysis', 'financial modeling', 'fundamental analysis', 'financial statements', 'stock investing', 'business analysis', 'value investor', 'Vancouver Value Investing'] } },

  { slug: 'cory-mitchell', name: 'Cory Mitchell', title: 'Trader and Trading Educator', credentials: 'CMT',
    expertise: ['Day Trading', 'Swing Trading', 'Forex Trading', 'Currency Markets', 'Technical Analysis', 'Trading Strategies', 'Risk Management', 'Financial Markets'],
    education: ['University of Lethbridge — Bachelor’s Degree in Finance'],
    certifications: ['Chartered Market Technician (CMT)'],
    social: { linkedin: 'https://www.linkedin.com/in/corymitchellcmt/', x: 'https://x.com/corymitc' },
    videoUrl: 'https://tradethatswing.com/',
    bio: 'Cory Mitchell is a professional trader, trading educator, and writer with extensive experience in day trading, swing trading, forex, currency markets, and technical analysis. He has been actively trading since 2005, focusing primarily on stocks and currencies.\n\nMitchell began his trading career as a proprietary trader, managing firm capital with compensation based on trading performance. After five years in proprietary trading, he transitioned to trading independently.\n\nAs a Chartered Market Technician (CMT), Mitchell specializes in short- to medium-term technical trading strategies. He has also worked with Fortune 500 companies and smaller businesses, helping them manage currency exposure and risk while identifying opportunities in foreign exchange markets.\n\nMitchell founded TradeThatSwing, an educational resource for day traders and swing traders. He has written extensively about financial markets and trading and has contributed to imperialpedia, TradeThatSwing.com, and TheStreet.com/Forex. He has also delivered lectures and workshops at Canadian Society of Technical Analysts conferences and has authored trading books and educational courses.\n\nMitchell earned his bachelor’s degree in finance from the University of Lethbridge.',
    seo: { title: 'Cory Mitchell | Day Trading, Forex & Technical Analysis Expert | Imperialpedia', description: 'Cory Mitchell is a professional trader and CMT specializing in day trading, swing trading, forex, currencies, technical analysis, and trading education.', keywords: ['Cory Mitchell', 'Cory Mitchell imperialpedia', 'day trading', 'swing trading', 'forex trading', 'currency trading', 'technical analysis', 'CMT', 'Chartered Market Technician', 'trading educator', 'trading strategies', 'risk management', 'stock trading', 'TradeThatSwing'] } },

  { slug: 'jiwon-ma', name: 'Jiwon Ma', title: 'Fact Checker', credentials: '',
    expertise: ['Cybersecurity', 'Geopolitical Analysis', 'International Affairs', 'Technology', 'Cryptocurrency', 'Political Economy', 'Research', 'Editing & Proofreading', 'Technology Policy', 'Privacy Policy'],
    education: ['Columbia University School of International and Public Affairs — Master of International Affairs', 'Lesley University — B.A.'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/jiwonma/' },
    bio: 'Jiwon Ma is a fact checker, editor, and research professional with experience spanning cybersecurity, international affairs, technology, geopolitical analysis, and cryptocurrency. She has worked as a fact checker for imperialpedia since 2022 and brings more than four years of editorial experience across a range of topics and sectors.\n\nBefore joining imperialpedia, Jiwon worked in cybersecurity and international security, including consulting for a global financial institution on cybersecurity policies. She also conducted research as a Research Analyst at the Belfer Center for Science and International Affairs, focusing on issues related to cybersecurity, international security, technology, and privacy policy.\n\nHer professional background combines editorial expertise with research and analytical experience in technology and security. Her areas of interest include cybersecurity threat intelligence, geopolitical developments, international affairs, cryptocurrency, political economy, and the intersection of technology and public policy.\n\nJiwon earned a Master of International Affairs from Columbia University’s School of International and Public Affairs, concentrating in International Security Policy with specializations in Technology, Media, and Communications and East Asia Regional policies. She also earned a Bachelor of Arts degree from Lesley University.',
    seo: { title: 'Jiwon Ma | Cybersecurity, Technology & Geopolitical Fact Checker | Imperialpedia', description: 'Jiwon Ma is a fact checker and research professional specializing in cybersecurity, international affairs, technology, cryptocurrency, geopolitical analysis, and public policy.', keywords: ['Jiwon Ma', 'Jiwon Ma imperialpedia', 'fact checker', 'cybersecurity', 'geopolitical analysis', 'international affairs', 'cryptocurrency', 'technology', 'political economy', 'cybersecurity research', 'technology policy', 'privacy policy', 'international security', 'financial cybersecurity'] } },

  { slug: 'nick-lioudis', name: 'Nick Lioudis', title: 'Financial Writer & Editor', credentials: '',
    expertise: ['Financial Journalism', 'Fintech', 'Personal Finance', 'Investing', 'Financial Markets', 'Business', 'Content Strategy', 'Publishing', 'Media Analytics'],
    education: ['Seton Hall University — B.A. in Journalism', 'The New School, Milano School of Policy, Management, and Environment — Master’s Degree'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/nickolas-lioudis/' },
    bio: 'Nick Lioudis is a journalist, writer, multimedia professional, and content strategist with more than 10 years of experience covering business, finance, and a range of economic and social topics.\n\nHis journalism has appeared in national and regional publications including amNY, The Star-Ledger, Morristown Daily Record, Honeysuckle Magazine, Nonprofit News, and Emerging Manager Monthly. He previously served as deputy editor of Financial Investment News, a publication focused on institutional investors, and has also worked in fintech as a content manager for Bread, a New York-based company providing consumer lending solutions.\n\nLioudis currently works as a content manager at Chartbeat, a technology company providing data and analytics to publishers. His work combines journalism, financial content, digital publishing, and audience analytics.\n\nHe is particularly interested in making complex financial information accessible and useful to a broad audience. His professional interests include financial literacy, fintech, investing, personal finance, financial markets, and the evolving relationship between technology and financial services.\n\nLioudis earned a Bachelor of Arts in Journalism from Seton Hall University and a master’s degree from the Milano School of Policy, Management, and Environment at The New School.',
    seo: { title: 'Nick Lioudis | Financial Writer, Editor & Fintech Expert | Imperialpedia', description: 'Nick Lioudis is a journalist and financial writer with 10+ years of experience covering finance, business, fintech, investing, publishing, and financial literacy.', keywords: ['Nick Lioudis', 'Nick Lioudis imperialpedia', 'financial writer', 'financial journalist', 'fintech', 'investing', 'personal finance', 'financial markets', 'business journalism', 'financial literacy', 'content strategy', 'institutional investing', 'publishing', 'media analytics'] } },

  { slug: 'thomas-j-catalano', name: 'Thomas J. Catalano', title: 'Financial Advisor', credentials: 'CFP, RIA',
    expertise: ['Financial Planning', 'Personal Finance', 'Investing', 'Retirement Planning', 'Estate Planning', 'Tax Planning', 'Insurance Planning', 'Debt', 'Loans', 'Mortgages', 'Portfolio Management', 'Trading', 'Wealth Management'],
    education: ['Pace University — MBA', 'New York University — Financial Planning'],
    certifications: ['Certified Financial Planner (CFP)', 'Registered Investment Adviser (RIA)', 'FINRA Series 7, 63, and 65 requirements completed'],
    social: { linkedin: 'https://www.linkedin.com/in/tomcatalano1/' },
    bio: 'Thomas J. Catalano is a financial advisor and wealth management professional with more than 30 years of experience in corporate leadership, financial planning, investing, and personal finance.\n\nBefore entering financial advisory services, Catalano held executive positions in sales, business development, marketing, and strategic planning within the Fortune 25 business environment. These roles helped him develop extensive experience in financial analysis, business strategy, and management.\n\nAs a wealth advisor, Catalano specializes in investment management, retirement planning, estate planning, tax planning, insurance planning, educational funding, and personal financial management. He works with clients to evaluate their financial circumstances and develop strategies aligned with their individual goals. His areas of financial planning include retirement accounts, investment portfolios, insurance, savings strategies, and education funding.\n\nCatalano is a Certified Financial Planner and Registered Investment Adviser. He has also completed the training and examination requirements for FINRA Series 7, 63, and 65.\n\nCatalano holds an MBA from Pace University in New York and completed financial planning education at New York University.',
    seo: { title: 'Thomas J. Catalano | Financial Advisor & Retirement Planning Expert | Imperialpedia', description: 'Thomas J. Catalano is a financial advisor with 30+ years of experience in financial planning, investing, retirement, insurance, estate planning, and personal finance.', keywords: ['Thomas J. Catalano', 'Thomas Catalano', 'Thomas J Catalano imperialpedia', 'financial advisor', 'CFP', 'registered investment adviser', 'financial planning', 'retirement planning', 'personal finance', 'investing', 'wealth management', 'estate planning', 'tax planning', 'insurance planning', 'portfolio management', 'FINRA Series 7', 'Series 63', 'Series 65'] } },

  { slug: 'yarilet-perez', name: 'Yarilet Perez', title: 'Fact Checker', credentials: '',
    expertise: ['Personal Finance', 'Investing', 'Real Estate', 'Financial Education', 'Fact-Checking', 'Journalism', 'News Production'],
    education: ['Master of Science in Journalism, Northwestern University Medill School of Journalism', 'The City College of New York'],
    certifications: [],
    social: { linkedin: 'https://www.linkedin.com/in/yariletp/' },
    bio: 'Yarilet Perez is a fact-checker and journalist with experience in broadcast reporting, news production, editing, and financial content. She has worked as a fact-checker for imperialpedia since 2020 and has updated more than 500 articles, helping ensure that financial information is accurate, clear, and reliable.\n\nYarilet began her career as a broadcast reporter, covering breaking news and politics in Washington, D.C., Chicago, and Hartford. She has prepared live newscasts, delivered breaking news, and contributed to media organizations including the Miami Herald and Univision. Her experience in journalism and financial content has strengthened her interest in personal finance, investing, and real estate.',
    seo: { title: 'Yarilet Perez | imperialpedia', description: 'Yarilet Perez is an imperialpedia fact-checker and journalist specializing in personal finance, investing, real estate, and financial education.', keywords: ['Yarilet Perez', 'imperialpedia', 'fact checker', 'personal finance', 'investing', 'real estate', 'financial education', 'journalism', 'financial content', 'financial fact checking'] } },

  { slug: 'anthony-battle', name: 'Anthony Battle', title: 'Certified Financial Planner', credentials: 'CFP®; ChFC®; CLU®; AFC®; RICP®; CRC',
    expertise: ['Financial Planning', 'Retirement Planning', 'Personal Finance', 'Investing', 'Life Insurance', 'Insurance', 'Accounting', 'Debt', 'Alternative Investments', 'Risk Management'],
    education: ['Bachelor of Business Administration in Accounting, Bernard M. Baruch College, CUNY'],
    certifications: ['CERTIFIED FINANCIAL PLANNER™ professional', 'Chartered Financial Consultant® (ChFC®)', 'Chartered Life Underwriter® (CLU®)', 'Accredited Financial Counselor® (AFC®)', 'Retirement Income Certified Professional® (RICP®)', 'Certified Retirement Counselor (CRC)'],
    social: { linkedin: 'https://www.linkedin.com/in/anthonybattle/' },
    bio: 'Anthony Battle is a financial planning professional with extensive experience in financial services, retirement planning, insurance, investing, and personal finance. He has spent his career serving both institutional and individual clients, developing comprehensive financial plans and helping individuals make informed retirement decisions. Anthony also presents financial planning seminars for municipal employees. Previously, he spent seven years in asset management working with private equity and hedge funds as a Fund Controller, overseeing financial reporting, investment valuations, and risk management. His professional experience includes roles with Bank of Bermuda, HSBC Corporate & Investment Bank, Tishman Speyer, McGladrey, and First Eagle Investment Management.',
    seo: { title: 'Anthony Battle, CFP® | imperialpedia', description: 'Anthony Battle is a financial planning professional and imperialpedia Financial Review Board member specializing in retirement planning, insurance, investing, personal finance, and risk management.', keywords: ['Anthony Battle', 'imperialpedia', 'CFP', 'financial planning', 'retirement planning', 'personal finance', 'investing', 'life insurance', 'insurance', 'accounting', 'debt', 'alternative investments', 'risk management'] } },

  { slug: 'samantha-silberstein', name: 'Samantha Silberstein', title: 'Financial Consultant / Financial Planner', credentials: 'CFP®; Certified Student Loan Professional; Enrolled Agent',
    expertise: ['Financial Planning', 'Investing', 'Student Loans', 'Personal Finance', 'Retirement Planning', 'Personal Taxes', 'Debt Management', 'Financial Education'],
    education: ['Bachelor’s Degree in Economics, Temple University', 'Minor in Business'],
    certifications: ['CERTIFIED FINANCIAL PLANNER™ professional', 'Certified Student Loan Professional', 'Enrolled Agent', 'CFA Level III Candidate'],
    social: { x: 'https://x.com/SammSilb' },
    bio: 'Samantha Silberstein is a Certified Financial Planner, Certified Student Loan Professional, and Enrolled Agent with expertise in financial planning, retirement, investing, student loans, personal finance, and taxes. As a financial consultant, she works with employees from nonprofit and higher education organizations, helping clients navigate retirement plans, student loans, budgeting, debt repayment, tax-advantaged savings, and other financial decisions. Samantha has also served as a financial planning educator with Dalton Education, where she teaches students pursuing the CFP curriculum and preparing for the CFP exam. Her previous experience includes roles with TD Ameritrade, Janney Montgomery Scott, Vanguard, and TIAA, spanning RIA relationship management, retirement plan consulting, income sales, fund management, and financial planning. She currently works with SLP Wealth, where she focuses on helping clients manage student and household debt while pursuing their long-term financial goals.',
    seo: { title: 'Samantha Silberstein, CFP® | imperialpedia', description: 'Samantha Silberstein is a financial planning professional and imperialpedia Financial Review Board member specializing in retirement planning, investing, student loans, personal finance, and taxes.', keywords: ['Samantha Silberstein', 'imperialpedia', 'CFP', 'financial planning', 'financial planner', 'retirement planning', 'investing', 'student loans', 'personal finance', 'taxes', 'debt management', 'financial education'] } },

  { slug: 'marguerita-m-cheng', name: 'Marguerita M. Cheng', title: 'Chief Executive Officer, Blue Ocean Global Wealth', credentials: 'CFP®; CRPC®; RICP®; CDFA®',
    expertise: ['Financial Planning', 'Personal Finance', 'Retirement Planning', 'Student Loans', 'Investing', 'Retirement Income', 'Divorce Financial Planning'],
    education: ['B.S. in Finance, University of Maryland, College Park', 'B.A. in East Asian Language and Japanese Literature, University of Maryland, College Park', 'studied at Keio University, Tokyo, Japan'],
    certifications: ['CERTIFIED FINANCIAL PLANNER™ professional (CFP®)', 'Chartered Retirement Planning Counselor℠ (CRPC®)', 'Retirement Income Certified Professional® (RICP®)', 'Certified Divorce Financial Analyst (CDFA®)'],
    social: { linkedin: 'https://www.linkedin.com/in/margueritacheng/', x: 'https://x.com/blueoceangw' },
    videoUrl: 'https://www.blueoceanglobalwealth.com/',
    bio: 'Marguerita M. Cheng is the Chief Executive Officer and co-founder of Blue Ocean Global Wealth. She is a Certified Financial Planner™ professional with extensive experience in financial planning, retirement planning, personal finance, investing, and student loans. Before co-founding Blue Ocean Global Wealth, Marguerita worked as a Financial Advisor at Ameriprise Financial and as an Analyst and Editor at Towa Securities in Tokyo, Japan. She serves on the Board of Directors of the Association for Divorce Financial Planners and has been recognized on imperialpedia’s 100 Top Financial Advisors list every year since 2017. Marguerita is also a CFP Board Ambassador and contributes to financial education and policy discussions. She is a regular columnist for Kiplinger and has served in leadership roles with the Financial Planning Association and CFP Board.',
    seo: { title: 'Marguerita M. Cheng, CFP® | imperialpedia', description: 'Marguerita M. Cheng is a CFP® professional, financial planner, and CEO of Blue Ocean Global Wealth specializing in retirement planning, personal finance, investing, and student loans.', keywords: ['Marguerita M. Cheng', 'imperialpedia', 'CFP', 'financial planner', 'Blue Ocean Global Wealth', 'financial planning', 'personal finance', 'retirement planning', 'student loans', 'investing', 'retirement income', 'divorce financial planning'] } },
];

function toPayload(a, index) {
  const payload = {
    name: a.name,
    slug: a.slug,
    title: a.title,
    bio: a.bio,
    expertise: a.expertise && a.expertise.length ? a.expertise : undefined,
    education: a.education && a.education.length ? a.education : undefined,
    certifications: a.certifications && a.certifications.length ? a.certifications : undefined,
    social: a.social && Object.keys(a.social).length ? a.social : undefined,
    seoMetadata: a.seo ? { title: a.seo.title, description: a.seo.description, keywords: a.seo.keywords } : undefined,
    sortOrder: index + 1,
  };
  if (a.credentials) payload.credentials = a.credentials;
  if (a.videoUrl) payload.videoUrl = a.videoUrl;
  // avatarUrl intentionally omitted for every author — no verified photo supplied.
  return payload;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function req(method, url, token, body, attempts = 5) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const r = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: body ? JSON.stringify(body) : undefined,
      });
      const data = await r.json().catch(() => ({}));
      if (r.status >= 500 && i < attempts - 1) { await sleep(400 * (i + 1)); continue; }
      return { status: r.status, data };
    } catch (e) {
      lastErr = e;
      await sleep(400 * (i + 1));
    }
  }
  throw lastErr || new Error('request failed after retries');
}

async function getToken() {
  if (CMS_TOKEN) return CMS_TOKEN;
  if (!PW) throw new Error('Set CMS_TOKEN (prod bearer) or SUPERADMIN_PASSWORD (local login) — see script header for usage.');
  const login = await req('POST', `${AUTH}/login`, null, { email: EMAIL, password: PW });
  const token = login.data?.data?.accessToken;
  if (!token) throw new Error('login failed: ' + JSON.stringify(login.data).slice(0, 200));
  return token;
}

async function main() {
  const payloads = AUTHORS.map(toPayload);

  if (DRY_RUN) {
    console.log(JSON.stringify({ ok: true, dryRun: true, site: SITE, base: BASE, count: payloads.length, payloads }, null, 2));
    return;
  }

  const token = await getToken();

  const existingRes = await req('GET', `${BASE}/authors`, token);
  const existing = new Set((existingRes.data?.data || []).map((a) => a.slug));

  let created = 0, skipped = 0, failed = 0;
  for (const payload of payloads) {
    if (existing.has(payload.slug)) { skipped++; continue; }
    const res = await req('POST', `${BASE}/authors`, token, payload);
    if (res.status === 201 || res.status === 200) created++;
    else if (res.status === 409) skipped++;
    else { failed++; console.error(`author ${payload.slug} -> ${res.status}`, JSON.stringify(res.data).slice(0, 300)); }
    await sleep(150);
  }

  console.log(JSON.stringify({ ok: true, site: SITE, base: BASE, created, skipped, failed, total: payloads.length }, null, 2));
}

main().catch((e) => { console.error('imperialpedia author seed failed:', e.message); process.exit(1); });
