
import React from "react";
import type { Metadata } from "next";
import Script from "next/script";
import { Inter, Libre_Franklin, Source_Serif_4 } from "next/font/google";
import { AuthProvider } from '@/context/AuthContext';
import { ThemeProvider } from '@/context/ThemeContext';
import { I18nProvider } from '@/i18n/I18nProvider';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/navbar';
import NotificationToastListener from '@/components/notifications/NotificationToastListener';
import ImpersonationBanner from '@/components/admin/ImpersonationBanner';
import { cmsGetAdsenseClient } from '@/lib/cms';
import UnifiedAnalytics from '@/components/UnifiedAnalytics';
import { GoogleAnalytics } from '@/components/GoogleAnalytics';
import { CookieConsentBanner } from '@/components/CookieConsentBanner';
import { cn } from '@/lib/utils';
import './globals.css';

// Editorial type system: Libre Franklin (Franklin-Gothic display, à la
// Investopedia/CNBC mastheads) + Inter (UI body) + Source Serif 4 (long-form
// article reading). Self-hosted via next/font — removes the render-blocking
// fonts.googleapis.com request + preconnects, adds automatic font-display:
// swap and preloading of the fonts actually used above the fold.
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-body',
  display: 'swap',
});
const libreFranklin = Libre_Franklin({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-headline',
  display: 'swap',
});
const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-serif',
  display: 'swap',
});

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://lawelitenetwork.com';
const CMS_SLUG = process.env.NEXT_PUBLIC_CMS_WEBSITE_SLUG || 'law-elite-network';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  icons: {
    icon: [
      { url: '/brand/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/brand/apple-icon.png',
  },
  title: {
    default: 'Law Elite Network | Global Legal Intelligence',
    template: '%s | Law Elite Network',
  },
  description:
    "The world's most distinguished legal knowledge and practitioner discovery platform. Find expert lawyers, manage cases, and access legal intelligence.",
  keywords: [
    'legal intelligence',
    'lawyer search',
    'legal consultation',
    'law firm directory',
    'legal advice',
    'attorney finder',
    'case management',
    'Law Elite Network',
  ],
  authors: [{ name: 'Law Elite Network', url: SITE_URL }],
  creator: 'Law Elite Network',
  publisher: 'Baalvion',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: 'Law Elite Network',
    title: 'Law Elite Network | Global Legal Intelligence',
    description:
      "The world's most distinguished legal knowledge and practitioner discovery platform.",
    // OG image is generated by src/app/opengraph-image.tsx (Next metadata file
    // convention) — no static /og-image.png asset is required.
  },
  twitter: {
    card: 'summary_large_image',
    site: '@lawelitenetwork',
    creator: '@lawelitenetwork',
    title: 'Law Elite Network | Global Legal Intelligence',
    description:
      "The world's most distinguished legal knowledge and practitioner discovery platform.",
    // Twitter image is generated by src/app/twitter-image.tsx (convention).
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: SITE_URL,
    types: { 'application/rss+xml': '/feed.xml' },
  },
};

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'LegalService',
  name: 'Law Elite Network',
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description:
    "The world's most distinguished legal knowledge and practitioner discovery platform.",
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer support',
    url: `${SITE_URL}/contact-us`,
  },
  sameAs: ['https://x.com/lawelitenetwork', 'https://www.linkedin.com/company/law-elite-network'],
};

const webSiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Law Elite Network',
  url: SITE_URL,
  description:
    "The world's most distinguished legal knowledge and practitioner discovery platform.",
  publisher: { '@type': 'Organization', name: 'Law Elite Network', url: SITE_URL },
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // AdSense publisher ID is managed in the CMS admin panel (Website → SEO →
  // Monetization); resolved server-side, hourly-cached, env-fallback inside.
  const ADSENSE_CLIENT = await cmsGetAdsenseClient();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(inter.variable, libreFranklin.variable, sourceSerif.variable)}
    >
      <head>
        {/* Google Consent Mode v2 -- must be pushed to dataLayer BEFORE gtag('js', ...)
            and gtag('config', ...) run (in GoogleAnalytics below) and before the AdSense
            loader in <body>, so no GA/ads cookie is set for a visitor who hasn't chosen
            yet. CookieConsentBanner updates these to 'granted' on accept; until then
            every visitor (EEA or not) defaults to denied, satisfying Google's EU User
            Consent Policy requirement for AdSense/Analytics. */}
        <Script id="consent-default" strategy="beforeInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            window.gtag = gtag;
            gtag('consent', 'default', {
              ad_storage: 'denied',
              ad_user_data: 'denied',
              ad_personalization: 'denied',
              analytics_storage: 'denied',
              wait_for_update: 500,
            });
          `}
        </Script>
        <GoogleAnalytics />
        <meta name="theme-color" content="#1e3a5f" />
        {ADSENSE_CLIENT && (
          <meta name="google-adsense-account" content={ADSENSE_CLIENT} />
        )}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteJsonLd) }}
        />
      </head>
      <body className="font-body antialiased selection:bg-blue-100 selection:text-blue-900 bg-background text-foreground overflow-x-hidden">
        {ADSENSE_CLIENT && (
          <Script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_CLIENT}`}
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
        )}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-6 focus:py-3 focus:bg-blue-700 focus:text-white focus:rounded-xl focus:font-bold focus:shadow-2xl"
        >
          Skip to main content
        </a>

        <ThemeProvider>
          <AuthProvider>
            <I18nProvider>
              <div className="flex flex-col min-h-screen relative">
                <Navbar />

                <main id="main-content" className="flex-1">
                  {children}
                </main>

                <NotificationToastListener />
                <ImpersonationBanner />
              </div>
              <Toaster />
            </I18nProvider>
          </AuthProvider>
        </ThemeProvider>
        <UnifiedAnalytics slug={CMS_SLUG} />
        <CookieConsentBanner />
      </body>
    </html>
  );
}
