
import React from "react";
import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import { AuthProvider } from '@/context/AuthContext';
import { ThemeProvider } from '@/context/ThemeContext';
import { I18nProvider } from '@/i18n/I18nProvider';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/navbar';
import NotificationToastListener from '@/components/notifications/NotificationToastListener';
import ImpersonationBanner from '@/components/admin/ImpersonationBanner';
import { cmsGetAdsenseClient } from '@/lib/cms';
import UnifiedAnalytics from '@/components/UnifiedAnalytics';
import { GoogleAnalytics } from '@/components/GoogleAnalytics';
import { CookieConsentBanner } from '@/components/CookieConsentBanner';
import { MobileAnchorAd } from '@/components/ads/MobileAnchorAd';
import { cn } from '@/lib/utils';
import './globals.css';

// Editorial type system: Libre Franklin (Franklin-Gothic display, à la
// Investopedia/CNBC mastheads) + Inter (UI body) + Source Serif 4 (long-form
// article reading). Vendored as local variable-font files (see src/fonts/)
// rather than next/font/google -- the latter fetches from fonts.gstatic.com
// at *build* time (not just runtime), and Vercel's build environment
// intermittently can't reach it ("Failed to fetch font file"), failing the
// whole production build. Local files remove that network dependency
// entirely. Each file is the same single latin-subset variable font Google
// was already serving for every weight in its range, downloaded straight
// from the same CDN URL next/font/google was using.
const inter = localFont({
  src: '../fonts/Inter-Variable.woff2',
  weight: '300 700',
  variable: '--font-body',
  display: 'swap',
});
const libreFranklin = localFont({
  src: '../fonts/LibreFranklin-Variable.woff2',
  weight: '400 900',
  variable: '--font-headline',
  display: 'swap',
});
const sourceSerif = localFont({
  src: '../fonts/SourceSerif4-Variable.woff2',
  weight: '400 700',
  variable: '--font-serif',
  display: 'swap',
});

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://lawelitenetwork.com';
const CMS_SLUG = process.env.NEXT_PUBLIC_CMS_WEBSITE_SLUG || 'law-elite-network';

// Search-console ownership proofs. Both no-op (render nothing) until the
// matching env var is set in Vercel with the real code from Google Search
// Console ("Settings → Ownership verification → HTML tag") / Bing Webmaster
// Tools ("Settings → Site verification → Meta tag") — pasting the code alone
// is not indexing, only the prerequisite for submitting the sitemap there.
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION?.trim();
const BING_SITE_VERIFICATION = process.env.BING_SITE_VERIFICATION?.trim();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  icons: {
    icon: [
      { url: '/brand/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/brand/apple-icon.png',
  },
  title: {
    default: 'Law Elite Network | Global Legal Education',
    template: '%s | Law Elite Network',
  },
  description:
    'An independent legal-education publisher. Plain-language guides to the law — organized by topic and jurisdiction — to help you understand your rights before you call a lawyer.',
  keywords: [
    'legal education',
    'plain-language legal guides',
    'legal guides by jurisdiction',
    'understand your rights',
    'lawyer search',
    'law firm directory',
    'legal advice',
    'Law Elite Network',
  ],
  authors: [{ name: 'Law Elite Network', url: SITE_URL }],
  creator: 'Law Elite Network',
  publisher: 'Baalvion',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: 'Law Elite Network',
    title: 'Law Elite Network | Global Legal Education',
    description:
      'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
    // OG image is generated by src/app/opengraph-image.tsx (Next metadata file
    // convention) — no static /og-image.png asset is required.
  },
  twitter: {
    card: 'summary_large_image',
    site: '@lawelitenetwork',
    creator: '@lawelitenetwork',
    title: 'Law Elite Network | Global Legal Education',
    description:
      'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
    // Twitter image is generated by src/app/twitter-image.tsx (convention).
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: SITE_URL,
    types: { 'application/rss+xml': '/feed.xml' },
  },
  ...((GOOGLE_SITE_VERIFICATION || BING_SITE_VERIFICATION) && {
    verification: {
      ...(GOOGLE_SITE_VERIFICATION && { google: GOOGLE_SITE_VERIFICATION }),
      ...(BING_SITE_VERIFICATION && { other: { 'msvalidate.01': BING_SITE_VERIFICATION } }),
    },
  }),
};

// 'Organization', not 'LegalService' -- LegalService is schema.org's type for
// an actual law firm/practitioner, which contradicts About Us's own "we are
// an educational publisher, not a law firm" disclosure. Misrepresenting the
// site's nature in structured data is exactly the kind of mismatch a review
// (AdSense or search quality) can flag.
const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Law Elite Network',
  legalName: 'Baalvion Industries Private Limited',
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description:
    'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
  foundingDate: '2025-03-11',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Yeshwant Avenue Building, NX Road, Y K Nagar, Virar West',
    addressLocality: 'Virar',
    addressRegion: 'Maharashtra',
    postalCode: '401303',
    addressCountry: 'IN',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer support',
    telephone: '+91-89512-84770',
    url: `${SITE_URL}/contact-us`,
  },
  sameAs: ['https://x.com/lawelitenetwork', 'https://www.linkedin.com/company/law-elite-network'],
};

const webSiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Law Elite Network',
  url: SITE_URL,
  description:
    'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
  publisher: { '@type': 'Organization', name: 'Law Elite Network', url: SITE_URL },
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // AdSense publisher ID is managed in the CMS admin panel (Website → SEO →
  // Monetization); resolved server-side, hourly-cached, env-fallback inside.
  const ADSENSE_CLIENT = await cmsGetAdsenseClient();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(inter.variable, libreFranklin.variable, sourceSerif.variable)}
    >
      <head>
        {/* Warm the connection (DNS + TLS) to the origins the LCP image (article/
            homepage hero) is actually sourced from before our own resize proxy
            (src/app/api/image/route.ts, see next.config.ts images.loader)
            fetches them, so that upstream fetch doesn't pay handshake latency
            on top of download time. */}
        <link rel="preconnect" href="https://api.baalvion.com" />
        <link rel="preconnect" href="https://firebasestorage.googleapis.com" crossOrigin="anonymous" />
        {/* Google Consent Mode v2 -- must be pushed to dataLayer BEFORE gtag('js', ...)
            and gtag('config', ...) run (in GoogleAnalytics below) and before the AdSense
            loader below, so no GA/ads cookie is set for a visitor who hasn't chosen yet.
            CookieConsentBanner updates these to 'granted' on accept; until then every
            visitor (EEA or not) defaults to denied, satisfying Google's EU User Consent
            Policy requirement for AdSense/Analytics. */}
        <Script id="consent-default" strategy="beforeInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            window.gtag = gtag;
            gtag('consent', 'default', {
              ad_storage: 'denied',
              ad_user_data: 'denied',
              ad_personalization: 'denied',
              analytics_storage: 'denied',
              wait_for_update: 500,
            });
          `}
        </Script>
        <GoogleAnalytics />
        <meta name="theme-color" content="#1e3a5f" />
        {ADSENSE_CLIENT && (
          <>
            <meta name="google-adsense-account" content={ADSENSE_CLIENT} />
            {/* AdSense's site-verification check regex-matches the raw HTML for a
                literal <script async src="...adsbygoogle.js...crossorigin...">
                tag. next/script's <Script> component -- for every strategy,
                including beforeInteractive -- never emits that literal tag; it
                registers the URL in a self.__next_s.push([...]) bootstrap array
                instead, so the crawler never finds a match. A plain native
                <script> element renders as literal HTML text, which is what
                the crawler is regex-matching. */}
            <script
              async
              src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_CLIENT}`}
              crossOrigin="anonymous"
            />
          </>
        )}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteJsonLd) }}
        />
      </head>
      <body className="font-body antialiased selection:bg-blue-100 selection:text-blue-900 bg-background text-foreground overflow-x-hidden">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-6 focus:py-3 focus:bg-blue-700 focus:text-white focus:rounded-xl focus:font-bold focus:shadow-2xl"
        >
          Skip to main content
        </a>

        <ThemeProvider>
          <AuthProvider>
            <I18nProvider>
              <div className="flex flex-col min-h-screen relative">
                <Navbar />

                <main id="main-content" className="flex-1">
                  {children}
                </main>

                <NotificationToastListener />
                <ImpersonationBanner />
              </div>
              <Toaster />
            </I18nProvider>
          </AuthProvider>
        </ThemeProvider>
        <UnifiedAnalytics slug={CMS_SLUG} />
        <CookieConsentBanner />
        <MobileAnchorAd />
      </body>
    </html>
  );
}
