
import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from '@/context/AuthContext';
import { ThemeProvider } from '@/context/ThemeContext';
import { I18nProvider } from '@/i18n/I18nProvider';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/navbar';
import NotificationToastListener from '@/components/notifications/NotificationToastListener';
import ImpersonationBanner from '@/components/admin/ImpersonationBanner';
import { cmsGetAdsenseClient } from '@/lib/cms';
import UnifiedAnalytics from '@/components/UnifiedAnalytics';
import { GoogleAnalytics } from '@/components/GoogleAnalytics';
import { CookieConsentBanner } from '@/components/CookieConsentBanner';
import { MobileAnchorAd } from '@/components/ads/MobileAnchorAd';
import { cn } from '@/lib/utils';
import './globals.css';

// Editorial type system: Libre Franklin (Franklin-Gothic display, à la
// Investopedia/CNBC mastheads) + Inter (UI body) + Source Serif 4 (long-form
// article reading). Vendored as local variable-font files (see src/fonts/)
// rather than next/font/google -- the latter fetches from fonts.gstatic.com
// at *build* time (not just runtime), and Vercel's build environment
// intermittently can't reach it ("Failed to fetch font file"), failing the
// whole production build. Local files remove that network dependency
// entirely. Each file is the same single latin-subset variable font Google
// was already serving for every weight in its range, downloaded straight
// from the same CDN URL next/font/google was using.
const inter = localFont({
  src: '../fonts/Inter-Variable.woff2',
  weight: '300 700',
  variable: '--font-body',
  display: 'swap',
});
const libreFranklin = localFont({
  src: '../fonts/LibreFranklin-Variable.woff2',
  weight: '400 900',
  variable: '--font-headline',
  display: 'swap',
});
const sourceSerif = localFont({
  src: '../fonts/SourceSerif4-Variable.woff2',
  weight: '400 700',
  variable: '--font-serif',
  display: 'swap',
});

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://lawelitenetwork.com';
const CMS_SLUG = process.env.NEXT_PUBLIC_CMS_WEBSITE_SLUG || 'law-elite-network';

// Search-console ownership proofs. Both no-op (render nothing) until the
// matching env var is set in Vercel with the real code from Google Search
// Console ("Settings → Ownership verification → HTML tag") / Bing Webmaster
// Tools ("Settings → Site verification → Meta tag") — pasting the code alone
// is not indexing, only the prerequisite for submitting the sitemap there.
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION?.trim();
const BING_SITE_VERIFICATION = process.env.BING_SITE_VERIFICATION?.trim();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  icons: {
    // SVG favicon — scales-of-justice mark; scales perfectly from 16px to 512px
    icon: [
      { url: '/brand/icon.svg', type: 'image/svg+xml' },
      // ICO fallback for older browsers / Windows taskbar pinning
      { url: '/favicon.ico', sizes: '48x48', type: 'image/x-icon' },
    ],
    // Apple Touch Icon — shown when user adds site to Home Screen on iPhone/iPad
    apple: [
      { url: '/brand/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    // Shortcut / PWA manifest icon
    shortcut: '/brand/icon.svg',
  },
  title: {
    default: 'Law Elite Network | Legal Guides & News',
    template: '%s | Law Elite Network',
  },
  description:
    'Law Elite Network — plain-language legal guides, court news, and expert analysis organized by practice area and jurisdiction. Understand your rights before you call a lawyer.',
  keywords: [
    'legal education',
    'legal guides',
    'law news',
    'court cases',
    'maritime injury law',
    'personal injury lawyer',
    'cruise ship accidents',
    'plain-language legal guides',
    'legal guides by jurisdiction',
    'understand your rights',
    'law firm directory',
    'Law Elite Network',
  ],
  authors: [{ name: 'Law Elite Network', url: SITE_URL }],
  creator: 'Law Elite Network',
  publisher: 'Law Elite Network — Baalvion Industries',
  // Explicit OG logo for Google Knowledge Panel and rich results
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: 'Law Elite Network',
    title: 'Law Elite Network | Legal Guides & News',
    description:
      'Plain-language legal guides, court news, and expert analysis — organized by practice area and jurisdiction.',
    images: [
      {
        url: `${SITE_URL}/logo.jpg`,
        width: 1260,
        height: 840,
        alt: 'Law Elite Network — Scales of Justice logo',
      },
    ],
    // Article-level OG image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    site: '@lawelitenetwork',
    creator: '@lawelitenetwork',
    title: 'Law Elite Network | Legal Guides & News',
    description:
      'Plain-language legal guides, court news, and expert analysis — organized by practice area and jurisdiction.',
    images: [`${SITE_URL}/logo.jpg`],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: SITE_URL,
    types: { 'application/rss+xml': '/feed.xml' },
  },
  ...((GOOGLE_SITE_VERIFICATION || BING_SITE_VERIFICATION) && {
    verification: {
      ...(GOOGLE_SITE_VERIFICATION && { google: GOOGLE_SITE_VERIFICATION }),
      ...(BING_SITE_VERIFICATION && { other: { 'msvalidate.01': BING_SITE_VERIFICATION } }),
    },
  }),
};

// 'Organization', not 'LegalService' -- LegalService is schema.org's type for
// an actual law firm/practitioner, which contradicts About Us's own "we are
// an educational publisher, not a law firm" disclosure. Misrepresenting the
// site's nature in structured data is exactly the kind of mismatch a review
// (AdSense or search quality) can flag.
const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Law Elite Network',
  legalName: 'Baalvion Industries Private Limited',
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description:
    'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
  foundingDate: '2025-03-11',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Yeshwant Avenue Building, NX Road, Y K Nagar, Virar West',
    addressLocality: 'Virar',
    addressRegion: 'Maharashtra',
    postalCode: '401303',
    addressCountry: 'IN',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer support',
    telephone: '+91-89512-84770',
    url: `${SITE_URL}/contact-us`,
  },
  sameAs: ['https://x.com/lawelitenetwork', 'https://www.linkedin.com/company/law-elite-network'],
};

const webSiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Law Elite Network',
  url: SITE_URL,
  description:
    'An independent legal-education publisher. Plain-language guides to the law, organized by topic and jurisdiction.',
  publisher: { '@type': 'Organization', name: 'Law Elite Network', url: SITE_URL },
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // AdSense publisher ID is managed in the CMS admin panel (Website → SEO →
  // Monetization); resolved server-side, hourly-cached, env-fallback inside.
  const ADSENSE_CLIENT = await cmsGetAdsenseClient();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(inter.variable, libreFranklin.variable, sourceSerif.variable)}
    >
      <head>
        {/* Warm the connection (DNS + TLS) to the origins the LCP image (article/
            homepage hero) is actually sourced from before our own resize proxy
            (src/app/api/image/route.ts, see next.config.ts images.loader)
            fetches them, so that upstream fetch doesn't pay handshake latency
            on top of download time. */}
        <link rel="preconnect" href="https://api.baalvion.com" />
        <link rel="preconnect" href="https://firebasestorage.googleapis.com" crossOrigin="anonymous" />
        <GoogleAnalytics />
        <meta name="theme-color" content="#1e3a5f" />
        {ADSENSE_CLIENT && (
          <meta name="google-adsense-account" content={ADSENSE_CLIENT} />
        )}
      </head>
      <body className="font-body antialiased selection:bg-blue-100 selection:text-blue-900 bg-background text-foreground overflow-x-hidden">
        {/* Google Consent Mode v2 defaults + the AdSense loader, emitted as one raw HTML string.
            Both tags are literal in the server HTML, in this order: the consent script runs first at
            parse time and the `defer` AdSense tag runs after it, and Google's raw-HTML site check still
            sees the tag (the google-adsense-account meta in <head> is the other verification path).
            They are deliberately NOT React children. AdSense's loader injects its own <script> next to
            the first script in the document, and when these two were JSX in <head> React could not match
            that extra node on hydration: error #418 on every page and a client re-render of the whole
            tree. dangerouslySetInnerHTML content is never reconciled, so hydration ignores it.
            Order matters here: keep consent first, and re-check view-source after any edit. */}
        <div
          hidden
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html:
              `<script id="consent-default">window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=gtag;gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',analytics_storage:'denied',wait_for_update:500});</script>` +
              (ADSENSE_CLIENT
                ? `<script defer src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(ADSENSE_CLIENT)}" crossorigin="anonymous"></script>`
                : ''),
          }}
        />
        {/* Structured data lives in the body, after the raw block above, so no React-owned <script>
            sits in <head> for AdSense's injected loader to land beside (see the hydration note above). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteJsonLd) }}
        />
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-6 focus:py-3 focus:bg-blue-700 focus:text-white focus:rounded-xl focus:font-bold focus:shadow-2xl"
        >
          Skip to main content
        </a>

        <ThemeProvider>
          <AuthProvider>
            <I18nProvider>
              <div className="flex flex-col min-h-screen relative">
                <Navbar />

                <main id="main-content" className="flex-1">
                  {children}
                </main>

                <NotificationToastListener />
                <ImpersonationBanner />
              </div>
              <Toaster />
            </I18nProvider>
          </AuthProvider>
        </ThemeProvider>
        <UnifiedAnalytics slug={CMS_SLUG} />
        <CookieConsentBanner />
        <MobileAnchorAd />
      </body>
    </html>
  );
}
