-- Generated by scripts/gen-rls-migration.js — fail-closed tenant RLS (R1).
-- schema=auth tenantColumn=org_id tables=oauth_clients,oauth_authorization_codes,oauth_refresh_tokens,api_keys
-- Apply as the MIGRATION/owner role; the runtime connects as baalvion_app.

BEGIN;

ALTER TABLE "auth"."oauth_clients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth"."oauth_clients" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "auth"."oauth_clients";
CREATE POLICY "tenant_isolation" ON "auth"."oauth_clients"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));

ALTER TABLE "auth"."oauth_authorization_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth"."oauth_authorization_codes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "auth"."oauth_authorization_codes";
CREATE POLICY "tenant_isolation" ON "auth"."oauth_authorization_codes"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));

ALTER TABLE "auth"."oauth_refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth"."oauth_refresh_tokens" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "auth"."oauth_refresh_tokens";
CREATE POLICY "tenant_isolation" ON "auth"."oauth_refresh_tokens"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));

ALTER TABLE "auth"."api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth"."api_keys" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "auth"."api_keys";
CREATE POLICY "tenant_isolation" ON "auth"."api_keys"
    USING ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)))
    WITH CHECK ((current_setting('app.tenant_bypass', true) = 'on' AND current_user <> 'baalvion_app') OR (current_setting('app.current_tenant', true) IS NOT NULL AND current_setting('app.current_tenant', true) <> '' AND "org_id"::text = current_setting('app.current_tenant', true)));

COMMIT;
