'use strict';
const router = require('express').Router();
router.use('/articles', require('./articlesRoutes'));
router.use('/assets', require('./assetsRoutes'));
router.use('/community', require('./communityRoutes'));
router.use('/creators', require('./creatorsRoutes'));
router.use('/leaderboard', require('./leaderboardRoutes'));
router.use('/calculators', require('./calculatorRoutes'));
router.use('/analytics', require('./analyticsRoutes'));
module.exports = router;
